### ISSUE TITLE
Custom Doctrine Types not Supported in SearchFilter

### ISSUE THREAD

**Issue by krcrawford** [api-platform/core#2380] opened 2018-12-13 21:59 UTC
As an example, when using a custom Doctrine type like `Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType`, and likely `Ramsey\Uuid\Doctrine\UuidBinaryType`, the `SearchFilter` class fails to convert these appropriately in the `Doctrine\ORM\Query#setParameter` and `Doctrine\ORM\Query#setParameters` operations.
Working on a PR now.

**Comment by soyuka** [comment] 2018-12-15 16:53
this should work I think. If not, we need to do the same "normalization" of query parameters as I did with route parameters (`:id` for example, see identifier normalizers). It'd be very clean, not sure if necessary.

**Comment by krcrawford** [comment] 2018-12-19 14:45
@soyuka Here is what I'm seeing:
`src/Bridge/Doctrine/Orm/Filter/SearchFilter.php (method: filterProperty)`
```
        ...
        if (1 === \count($values)) {
            $queryBuilder
                ->andWhere(sprintf('%s.%s = :%s', $associationAlias, $associationField, $valueParameter))           
                ->setParameter($valueParameter, $values[0]); // no explicit type conversion
        } else {
            $queryBuilder
                ->andWhere(sprintf('%s.%s IN (:%s)', $associationAlias, $associationField, $valueParameter))
                ->setParameter($valueParameter, $values); // no explicit type conversion
        }
    }
```
The PR I'll propose approaches the problem with the following solution:
```
        ...

        $associatedMetadata = $this->getClassMetadata($metadata->getAssociationMapping($field)['targetEntity']);
        $type = $associatedMetadata->getFieldMapping('id')['type'];

        if (1 === \count($values)) {
            $queryBuilder
                ->andWhere(sprintf('%s.%s = :%s', $associationAlias, $associationField, $valueParameter))           
                ->setParameter($valueParameter, $values[0], $type);
        } else {
            $queryBuilder
                ->andWhere(sprintf('%s.%s IN (:%s)', $associationAlias, $associationField, $valueParameter))
                ->setParameter($valueParameter, $values, $type);
        }
    }
```
As a test, the above works. I'm just working on test coverage for it now. If not here, then where would you suggest I focus on for providing a richer solution to binary IDs?

**Comment by soyuka** [comment] 2018-12-20 08:18
```
        $type = $associatedMetadata->getFieldMapping('id')['type'];
```

hard-coded `id` isn't such a good idea :P. 

Are you sure that the type isn't correct? This should def work out of the box, anyway adding the type is also a good idea.

**Comment by krcrawford** [comment] 2019-01-03 16:53
Agreed on the explicit I'd, so I'll look for the joinColumn attribute in the PR

**Comment by brunoric** [comment] 2019-05-21 08:24
Hi, I have the same issue here. @krcrawford, did you manage to fix this or found any workaround?
Regards,
Bruno

**Comment by krcrawford** [comment] 2019-05-21 15:48
@brunoric for the sake of time, I just created my own copy of SearchFilter and changed the method according to the above proposal.

**Comment by teohhanhui** [comment] 2019-05-21 17:08
Actually it's a bug in ramsey/uuid-doctrine: https://github.com/ramsey/uuid-doctrine/pull/72

**Comment by farazive** [comment] 2019-06-03 05:13
> Actually it's a bug in ramsey/uuid-doctrine: [ramsey/uuid-doctrine#72](https://github.com/ramsey/uuid-doctrine/pull/72)

It doesn't seem like that would should affect this. I added the following to code to `\Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType`

```php
    public function getBindingType()
    {
        return ParameterType::BINARY;
    }
```
But doctrine does not resolve the type when you use `setParameter` so it has no affect. 

# The Bug

To reproduce this bug have user class with Id type set to 'uuid_binary_ordered_time'.

My user class id is as below

```php
class User
{
    /**
     * @var \Ramsey\Uuid\UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(name="uuid", type="uuid_binary_ordered_time", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidOrderedTimeGenerator")
     */
    public $id;

    ....
```
and doctrine.yaml as follows:
```yaml
doctrine:
    dbal:
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType

        connections:
            my_connection:
                mapping_types:
                    uuid_binary_ordered_time: binary

```
Route `/users/{id}` where id is a uuid works great. 
Route `users?id=uuid` does not work. 

For the first case, everything works fine because api-platform converts the ids from strings to UUID objects for item operations  in `\ApiPlatform\Core\EventListener\ReadListener::onKernelRequest`.

But no such conversion occurs for collection operations and the string value is directly set as the parameter. This always results in an empty result set. 

Since Api-Platform supports Ramsey's UUID's out of the box, it can be assumed this is a bug.

**Comment by farazive** [comment] 2019-06-04 01:26
Also, the solution [above](https://github.com/api-platform/core/issues/2380#issuecomment-448620307) is applied only to ORM search filters. Which means it would need another implementation for ODMs. Shouldn't we resolve the ids in ReadListener.php like we do for itemOperations?

**Comment by soyuka** [comment] 2021-03-02 15:31
Closing this, IMHO when you have custom doctrine types it's hard to satisfy every need with our default filters and I suggest to build your own.

**Closed** 2021-03-02 15:31 UTC
Labels: wontfix
