### ISSUE TITLE
Subresource in swagger didn't have 'page' field.

### ISSUE THREAD

**Issue by ln-e** [api-platform/core#1650] opened 2018-01-15 15:13 UTC
Although there is enabled pagination:

```json
{
  "@context": "/api/contexts/Task",
  "@id": "/api/projects/3/tasks",
  "@type": "hydra:Collection",
  "hydra:member": [
    ...
  ],
  "hydra:totalItems": 33,
  "hydra:view": {
    "@id": "/api/projects/3/tasks?page=1",
    "@type": "hydra:PartialCollectionView",
    "hydra:first": "/api/projects/3/tasks?page=1",
    "hydra:last": "/api/projects/3/tasks?page=2",
    "hydra:next": "/api/projects/3/tasks?page=2"
  },
}
```

api-platform/core: v2.1.4

**Comment by ln-e** [comment] 2018-04-24 13:12
There is pagination in response. 
But there isn't page field in swagger. 

![2018-04-24_16-06-59](https://user-images.githubusercontent.com/2379195/39189046-f34b5b6e-47d9-11e8-9e69-0278cc3fc06f.png)

**Comment by JumpIfBelow** [comment] 2018-05-16 06:33
I actually have the same issue here: a subresource does not seem to have pagination activated.
I'll check the sources if I could where this issue belongs to. It is kinda weird that it is rendering in such a way. If I find a fix quickly, I'll do a merge request.

**Comment by JumpIfBelow** [comment] 2018-05-16 08:59
Okay, so part of the problem actually is that I've named the subresource operation on my entity `api_users_rights_get_subresource` while API Platform is generating `api_users_rights_get_subresourceRightCollection`. I think I've been misled to the first name because I used the route name. But how to know this? I only discovered after dumping data in the core, maybe there is a lack of information somewhere (I'm not blaming here, just trying to know)

The result of some operations made by the core is clearer now, but the final result seems to be the same for the documentation. Meanwhile, the result seems fixed: I can manually do the request with the page parameter.

Still, what is happening in `Swagger\Serializer\DocumentationNormalizer.php:197` seems a bit confusing for me. I've seen the array beeing filled with two new entries in only one iteration. Some data are altered between what the `getPathOperation` returns and the storage in  `$paths` variable. I'm not able to understand it more by myself.

**Comment by dunglas** [comment] 2018-05-16 09:25
We had a discussion about pagination with @sroze recently. We thought it would be nice to implement it has filters instead of this custom logic.

Anyway, it looks like a bug to me. The Swagger Normalizer probably not handle pagination for resources.

**Comment by JumpIfBelow** [comment] 2018-05-16 13:35
This issue still hurts my brain to understand it completely.
So, by changing the name as I said above for `api_users_rights_get_subresourceRightCollection`, what I've done is basically saying goodbye to any custom configuration for this subresource. It means this name has nothing to do to customize the subresource. In the same time, the pagination is now active, the configuration is auto-generated.

If I use the `api_users_rights_get_subresource`, I am able to add some special things, like authorization. But somewhere in the code, the pagination ability is lost, so no more paginated result for this subresource.

So, the issue is about *ToMany subresources, with the `Swagger\Serializer\DocumentationNormalizer` missing the generated name route. It adds a `<resource name>Collection` sufix to the route name that makes the whole thing failing to provide a pagination. I guess this suffix should not be there, as it clearly is a conflict between auto-generated and customized subresources parameters.

**Comment by soyuka** [comment] 2019-04-07 09:05
Closing in favor of https://github.com/api-platform/core/issues/2706

**Closed by soyuka** 2019-04-07 09:05 UTC
Labels: question
