### ISSUE TITLE
Doctrine exception after updating api-platform/core to v2.4.2

### ISSUE THREAD

**Issue by RikudouSage** [api-platform/core#2730] opened 2019-04-12 16:44 UTC
After updating from `v2.3.6` to `v2.4.2` I get an exception when I add this to the query builder via `QueryCollectionExtensionInterface::applyToCollection()` method:

```php
$queryBuilder
        ->innerJoin(Company::class, 'c', Join::WITH, "{$rootAlias}.company = c")
        ->andWhere(':currentUser MEMBER OF c.users')
        ->setParameter('currentUser', $currentUser);
```

If I comment out the line ` ->andWhere(':currentUser MEMBER OF c.users')` the excpetion is not thrown.

The resulting SQL is:

```sql
SELECT 
  DISTINCT c0_.id AS id_0, 
  c0_.id AS id_1 
FROM 
  clients c0_ 
  INNER JOIN companies c1_ ON (c0_.company_id = c1_.id) 
WHERE 
  c0_.id IN (
    SELECT 
      c2_.id 
    FROM 
      clients c2_ 
      INNER JOIN companies c3_ ON (c2_.company_id = c1_.id) 
    WHERE 
      EXISTS (
        SELECT 
          1 
        FROM 
          users u4_ 
        WHERE 
          c3_.id = u4_.company_id 
          AND u4_.id = ?
      )
  ) 
ORDER BY 
  c0_.id ASC 
LIMIT 
  30
```

And the error is:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c1_.id' in 'on clause'`

In version `v2.3.6` the resulting SQL from the same code was:

```sql
SELECT 
  DISTINCT c0_.id AS id_0, 
  c0_.id AS id_1 
FROM 
  clients c0_ 
  INNER JOIN companies c1_ ON (c0_.company_id = c1_.id) 
WHERE 
  EXISTS (
    SELECT 
      1 
    FROM 
      users u2_ 
    WHERE 
      c1_.id = u2_.company_id 
      AND u2_.id = ?
  ) 
ORDER BY 
  c0_.id ASC 
LIMIT 
  30
```

The SQL from previous version worked as expected.

**Comment by antograssiot** [comment] 2019-04-12 16:49
The quick fix for you might be to change the priority of your extention to a number between -18 and -31.

**Comment by RikudouSage** [comment] 2019-04-12 23:11
Is there any more permanent solution?

**Comment by antograssiot** [comment] 2019-04-13 06:12
I'll have a look at it when I'll get time but it likely comes from the FilterEagerLoadingExtension.
you can also set `force_eager` attribute to false.

**Comment by antograssiot** [comment] 2019-04-13 10:18
Ok I've been looking into this, and that's indeed a case pretty hard to handle.
I've been able to reproduce in [a test](https://github.com/antograssiot/core/commit/ff4f3138d504474094e4c166dd8c189876fb9da3) but I don't think we'll be able to support this scenario.

The root cause is that aliases are replaced in the subqueries if it matches `alias.` [here](https://github.com/api-platform/core/blob/bc0806be383a6fc6820a1230bbddd3ea29542ac7/src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php#L141-L144) but we can replace aliases only.

Then has explained, I think you have 3 options:
- Set a custom negative priority to your Extension to get the exact original behavior
- Use fetch-eager false
- Change your innerJoin to `->innerJoin(Company::class, 'c', Join::WITH, "{$rootAlias}.company = c.id")`  (what I've done in the test)

Do you see any other solution @soyuka @teohhanhui  ?

**Comment by RikudouSage** [comment] 2019-04-18 00:08
Thanks for the solutions.

**Comment by athos7933** [comment] 2019-06-26 11:38
With Api Platform 2.4 the `$queryBuilder->getAllAliases()`only contain the root alias.
With the 2.3.* all aliases contains alias of the fetch eager properties.

Any idea why now he contains only root alias. Any workaround ?

I try all solutions posted by @antograssiot but allAlias contains each time just root alias.

**Comment by Cethy** [comment] 2020-02-03 13:28
I encountered the same problem. The error is really cryptic.
Might be worth a note in the Query extension documentation.

(I used `force_eager: false`)

**Comment by soyuka** [comment] 2020-02-18 15:04
Could you help us update the docs?

**Comment by ahmed-bhs** [comment] 2020-10-25 20:43
@RikudouSage thank you so mush for the report, I'm working on a custom filter and I had the same issue:

* Setting negative priority to my service didn't solve the problem.
* disable eager mode, worked like a charm.
* Change your innerJoin to what exactly could you specify what did you change ?

**Comment by soyuka** [comment] 2021-02-23 14:17
Closing I recommend to disable force_eager and use your own queries for complex data retrieval.

**Closed by soyuka** 2021-02-23 14:17 UTC
