### ISSUE TITLE
Assert\NotBlank() doesn't prevent AbstractItemNormalizer error

### ISSUE THREAD

**Issue by kate-kate** [api-platform/core#1070] opened 2017-04-20 14:08 UTC
Hi guys! I have an entity with related field like this:
```php
    /**
     * @Groups({"dashboard","create_manual"})
     * @Assert\NotBlank(groups={"create_manual"})
     *
     * @ORM\ManyToOne(targetEntity="Campaign")
     */
    private $campaign;
```
where ```"create_manual"``` is a denormalization context group.

And then comes PUT request with ```"campaign":""``` (because there is a select in the frontend, which is sending campaign IRI from dropdown or empty string if user doesn't choose any).

 I expected validation error for this variant, but I get error: ```Type error: Argument 2 passed to ApiPlatform\Core\Metadata\Property\Factory\CachedPropertyMetadataFactory::create() must be of the type string, integer given, called in /path-to-my-project/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php on line 150```.

 I saw exactly the same error, once I tried to create embedded entity and have forgotten to use correct ```denormalization_context```. 

But I don't expect any objects here. I'm waiting for correct IRI or at least empty string, which may cause validation error. 

So, what's wrong?

**Comment by bwegrzyn** [comment] 2017-04-21 03:43
I'm guessing the error is caused by strict types being declared on all files in api platform recently. I'm not sure why its trying to pass an integer though.

Can you post the full error?

**Comment by kate-kate** [comment] 2017-04-21 07:45
@bwegrzyn of course, validation groups are not the same as groups on the normalization/denormalization context:) But I named them the same (it seems more simple for me). This is full ```@ApiResource``` annotation of my entity:
```php
/**
 * @ApiResource(attributes={
 *     "validation_groups"={"create_manual"},
 *     "normalization_context"={"groups"={"dashboard"}},
 *     "denormalization_context"={"groups"={"create_manual"}},
 *     "pagination_client_enabled"=false,
 *     "filters"={"job.search", "job.date", "job.order"}
 * })
 */
```

And here is the full error response:
```
{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Deserialization for the format html is not supported",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/Users/kate/htdocs/api_tryoup/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php",
      "line": 127,
      "args": []
    },
    {
      "namespace": "Symfony\\Component\\Serializer",
      "short_class": "Serializer",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "function": "deserialize",
      "file": "/Users/kate/htdocs/api_tryoup/vendor/api-platform/core/src/EventListener/DeserializeListener.php",
      "line": 69,
      "args": [
        [
          "string",
          "{\n   \"externalTelephone\":\"/api/external_telephones/42\",\n   \"campaign\":\"\",\n   \"category\":\"/api/categories/7\",\n   \"description\":\"testrtyuiuytrertyu\",\n   \"status\":\"cancelled\",\n   \"technician\":\"/api/users/4\"\n}"
        ],
        [
          "string",
          "AppBundle\\Entity\\Job"
        ],
        [
          "string",
          "html"
        ],
        [
          "array",
          {
            "item_operation_name": [
              "string",
              "put"
            ],
            "api_allow_update": [
              "boolean",
              true
            ],
            "resource_class": [
              "string",
              "AppBundle\\Entity\\Job"
            ],
            "request_uri": [
              "string",
              "/api/jobs/54"
            ],
            "groups": [
              "array",
              [
                [
                  "string",
                  "create_manual"
                ]
              ]
            ],
            "object_to_populate": [
              "object",
              "AppBundle\\Entity\\Job"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\EventListener",
      "short_class": "DeserializeListener",
      "class": "ApiPlatform\\Core\\EventListener\\DeserializeListener",
      "type": "->",
      "function": "onKernelRequest",
      "file": null,
      "line": null,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "call_user_func",
      "file": "/Users/kate/htdocs/api_tryoup/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php",
      "line": 106,
      "args": [
        [
          "array",
          [
            [
              "object",
              "ApiPlatform\\Core\\EventListener\\DeserializeListener"
            ],
            [
              "string",
              "onKernelRequest"
            ]
          ]
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "WrappedListener",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
      "type": "->",
      "function": "__invoke",
      "file": null,
      "line": null,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "call_user_func",
      "file": "/Users/kate/htdocs/api_tryoup/var/cache/dev/classes.php",
      "line": 3272,
      "args": [
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "doDispatch",
      "file": "/Users/kate/htdocs/api_tryoup/var/cache/dev/classes.php",
      "line": 3187,
      "args": [
        [
          "array",
          [
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ]
          ]
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/Users/kate/htdocs/api_tryoup/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php",
      "line": 136,
      "args": [
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "TraceableEventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/Users/kate/htdocs/api_tryoup/var/cache/dev/classes.php",
      "line": 4201,
      "args": [
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handleRaw",
      "file": "/Users/kate/htdocs/api_tryoup/var/cache/dev/classes.php",
      "line": 4171,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handle",
      "file": "/Users/kate/htdocs/api_tryoup/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php",
      "line": 168,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ],
        [
          "boolean",
          true
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "Kernel",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "function": "handle",
      "file": "/Users/kate/htdocs/api_tryoup/web/app_dev.php",
      "line": 33,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ]
      ]
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "require",
      "file": "/Users/kate/htdocs/api_tryoup/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php",
      "line": 40,
      "args": [
        [
          "string",
          "/Users/kate/htdocs/api_tryoup/web/app_dev.php"
        ]
      ]
    }
  ]
}
```

**Comment by kate-kate** [comment] 2017-04-21 08:10
Also I've created test with empty string passed to campaign and debugged it. At first ```setAttributeValue()``` method receive "campaign" as well, but then something happens, and it really get 0 as attribute. Maybe I will found what's wrong, looks like an empty string was deserialized as attribute named 0.

**Comment by bwegrzyn** [comment] 2017-04-21 16:33
Nice job on debugging the issue. Can you open a pull request with the fix and some additional tests?

**Comment by dunglas** [comment] 2017-04-24 20:10
Thanks you for the debugging and the very clear explanation @kate-kate.

**Comment by dunglas** [comment] 2017-04-24 20:14
IIUC, the problem is that the type is not enforced here. It should be an array or an IRI, nothing else. Testing for `''` only partially fix the problem. In this specific case, we should not let other normalizers a change because only an IRI or an array containing a valid document is expected.

**Comment by kate-kate** [comment] 2017-04-25 06:40
hello @dunglas, glad that you noticed this issue. IMO after InvalidArgumentException there should not be "a chance to other normalizers (e.g.: DateTimeNormalizer)", cause we normalizing relation and only string variant is IRI. But also it should raise validation error, not an exception, I think, because in the web in dropdowns default value often will be ''

**Comment by Padam87** [comment] 2017-06-04 12:06
I think I have found a related issue.

I have created a test app, just to look at the api platform before my next major project. I have a `title` field:

```php
    /**
     * @var string
     *
     * @ORM\Column()
     * @Assert\NotBlank()
     * @Serializer\Groups({"test"})
     */
    protected $title;
```

If the post contains a `null` value:
`The type of the "title" attribute must be "string", "NULL" given.`

If an empty string is posted:
Not blank message, and a list of violations, as it should be.

**Comment by samusenkoiv** [comment] 2017-08-11 15:24
Any updates on the issue? Why https://github.com/api-platform/core/pull/1077 is not merged yet?

**Comment by kate-kate** [comment] 2017-09-12 12:15
Hi again @dunglas and others! Apparently, I have participated yet in another project on API Platform. After I've created a huge test for my code, I saw this error and was referred to this issue again :)
As I remember, after some code style enhancements and @soyuka advices, my fix has passed all tests and I even made one more test for this exact problem. So, is anything missing to merge it?

**Comment by sverraest** [comment] 2017-12-07 14:14
Running into the exact same issue. Anything blocking this merge?

**Comment by Nightbr** [comment] 2018-03-07 16:40
Same error here on a nullable phoneNumber.
```
    /**
     * @var string
     *
     * @PhoneNumberAssert
     * @ORM\Column(type="phone_number", nullable=true)
     * @Groups({"out", "recruiter_in", "in"})
     */
    private $phoneNumber;
```
When you try to PUT the phoneNumber to null:
`{"phoneNumber":null}`

We get an error:

```
{
    "@context": "/app_dev.php/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "The type of the \"phoneNumber\" attribute must be \"string\", \"NULL\" given.",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/var/www/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
            "line": 227,
            "args": []
        },
        {
            "namespace": "ApiPlatform\\Core\\Serializer",
            "short_class": "AbstractItemNormalizer",
            "class": "ApiPlatform\\Core\\Serializer\\AbstractItemNormalizer",
            "type": "->",
            "function": "validateType",
            "file": "/var/www/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
            "line": 203,
            "args": [
                [
                    "string",
                    "phoneNumber"
                ],
                [
                    "object",
                    "Symfony\\Component\\PropertyInfo\\Type"
                ],
                [
                    "null",
                    null
                ],
                [
                    "string",
                    "json"
                ]
            ]
        },
```

**Comment by soyuka** [comment] 2019-04-06 15:23
https://github.com/symfony/validator/commit/e9cf9f4401fa1e6262360a80502b5acede5a937c should fix this issue

**Closed by soyuka** 2019-04-06 15:23 UTC
Labels: question
