### ISSUE TITLE
Attempted to load interface "ResourceClassResolverInterface" from namespace "ApiPlatform\Api"

### ISSUE THREAD

**Issue by KalinichenkoRoman** [api-platform/core#5558] opened 2023-04-21 14:38 UTC
**API Platform version(s) affected**: 3.1.8

**Description**  

```
Script assets:install --symlink %PUBLIC_DIR% returned with error code 255
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#17415
!!    #message: """
!!      Attempted to load interface "ResourceClassResolverInterface" from namespace "ApiPlatform\Api".\n
!!      Did you forget a "use" statement for "ApiPlatform\Metadata\ResourceClassResolverInterface"?
!!      """
!!    #code: 0
!!    #file: "./vendor/api-platform/core/src/Api/ResourceClassResolver.php"
!!    #line: 28
```

**How to reproduce**  
`composer install`

composer.json
```json

    "require": {
        "php": "^8.1",
        "ext-ctype": "*",
        "ext-curl": "*",
        "ext-iconv": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "api-platform/core": "^3.1",
...
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink %PUBLIC_DIR%": "symfony-cmd",
            "elfinder:install": "symfony-cmd"
        },
...

```

**Comment by frenci8** [comment] 2023-04-21 17:48
I have the same issue, php 8.2.3, api-platform/core 3.18 , symfony 6.2.9. This error only occurs for the version 3.1.8 of api-platform/core, 3.1.7 works fine

> Script assets:install %PUBLIC_DIR% returned with error code 255
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#9948
!!    #message: """
!!      Attempted to load interface "ResourceClassResolverInterface" from namespace "ApiPlatform\Api".\n
!!      Did you forget a "use" statement for "ApiPlatform\Metadata\ResourceClassResolverInterface"?
!!      """
!!    #code: 0
!!    #file: "./vendor/api-platform/core/src/Api/ResourceClassResolver.php"
!!    #line: 28
!!    trace: {
!!      ./vendor/api-platform/core/src/Api/ResourceClassResolver.php:28 { …}
!!      ./vendor/composer/ClassLoader.php:582 { …}
!!      ./vendor/composer/ClassLoader.php:433 { …}
!!      ./vendor/symfony/error-handler/DebugClassLoader.php:300 { …}
!!      ./var/cache/dev/ContainerSECvaDO/App_KernelDevDebugContainer.php:2012 {
!!        ContainerSECvaDO\App_KernelDevDebugContainer->getApiPlatform_ResourceClassResolverService()
!!        › {
!!        ›     return $this->privates['api_platform.resource_class_resolver'] = new \ApiPlatform\Api\ResourceClassResolver(($this->privates['api_platform.metadata.resource.name_collection_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_NameCollectionFactory_CachedService()));
!!        › }
!!        arguments: {
!!          $class: "ApiPlatform\Api\ResourceClassResolver"
!!        }
!!      }
!!      ./var/cache/dev/ContainerSECvaDO/App_KernelDevDebugContainer.php:1918 { …}
!!      ./var/cache/dev/ContainerSECvaDO/App_KernelDevDebugContainer.php:1965 { …}
!!      ./var/cache/dev/ContainerSECvaDO/getRouting_LoaderService.php:48 { …}
!!      ./var/cache/dev/ContainerSECvaDO/App_KernelDevDebugContainer.php:722 { …}
!!      ./vendor/symfony/dependency-injection/Container.php:382 { …}
!!      ./vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40 { …}
!!      ./vendor/symfony/framework-bundle/Routing/Router.php:65 { …}
!!      ./vendor/easycorp/easyadmin-bundle/src/Cache/CacheWarmer.php:33 { …}
!!      ./vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:96 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:526 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:709 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:122 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:148 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:69 { …}
!!      ./vendor/symfony/console/Application.php:168 { …}
!!      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
!!      ./vendor/autoload_runtime.php:29 { …}
!!      ./bin/console:11 { …}
!!    }
!!  }
!!  2023-04-21T17:44:10+00:00 [critical] Uncaught Error: Interface "ApiPlatform\Api\ResourceClassResolverInterface" not found
!!

**Comment by soyuka** [comment] 2023-04-22 08:43
I didn't change that since 3.1.6, 

https://github.com/api-platform/core/blob/3.1/src/Api/ResourceClassResolverInterface.php
https://github.com/api-platform/core/blob/3.1/src/Metadata/ResourceClassResolverInterface.php (correct one but the old one should still exists)

`composer dump-autoload` maybe?

**Comment by BurningDog** [comment] 2023-04-22 09:01
`composer update` gave me the same problem as described in the issue.

`composer dump-autoload` followed by `composer update` resulted in the same issue.

The problem is in:
https://github.com/api-platform/core/blob/main/src/Api/ResourceClassResolver.php#L28

It implements `ResourceClassResolverInterface` but is missing a `use` statement, which should be:

```php
use ApiPlatform\Metadata\ResourceClassResolverInterface;
```

**Comment by D3VinEd** [comment] 2023-04-22 09:58
> ```
> use ApiPlatform\Metadata\ResourceClassResolverInterface;
> ```
It's not fixed by implement this line of code.
Here's the result:
`ApiPlatform\Metadata\Property\Factory\IdentifierPropertyMetadataFactory::__construct(): Argument #1 ($resourceClassResolver) must be of type ApiPlatform\Api\ResourceClassResolverInterface, ApiPlatform\Api\ResourceClassResolver given, called in /var/www/project/var/cache/dev/ContainerTNl6IfA/App_KernelDevDebugContainer.php on line 1540`

**Comment by souna23** [comment] 2023-04-22 12:39
any solution ??

**Comment by olivier1980** [comment] 2023-04-23 08:54
> `composer update` gave me the same problem as described in the issue.
> 
> `composer dump-autoload` followed by `composer update` resulted in the same issue.
> 
> The problem is in: https://github.com/api-platform/core/blob/main/src/Api/ResourceClassResolver.php#L28
> 
> It implements `ResourceClassResolverInterface` but is missing a `use` statement, which should be:
> 
> ```
> use ApiPlatform\Metadata\ResourceClassResolverInterface;
> ```

The `use` statement is not needed as both the class and the interface share the same directory/namespace.

I got the error too after installing a new package (symfony/debug) but after a refresh and some code browsing it went away by itself. Pretty weird, probably some internal cache issue or something. 

Related possibly: `ResourceClassResolverInterface` does a `interface_exists` without using the return value, that seems buggy as well..although it's always should defining the interface at the moment.

**Comment by olivier1980** [comment] 2023-04-23 09:04
I had the same problem as well, but it went away by itself..possibly some internal cache issue or something.

Note that `Api\ResourceClassResolver` is deprecated, and `Api\Metadata\ResourceClassResolver` should be used..so this error is probably due to Symfony not yet switching to the new class internally after an update.

**Comment by dorantor** [comment] 2023-04-23 09:10
`composer dump-autoload` helps in short term. After it first call is working, but next one is not.

I have basic IndexController. First call:
```
bin/console router:match /index
                                        
 [OK] Route "api_entrypoint" matches
```
Second call, right after the first one:
```
 bin/console router:match /index

In ResourceClassResolver.php line 28:
                                                                                                  
  Attempted to load interface "ResourceClassResolverInterface" from namespace "ApiPlatform\Api".  
  Did you forget a "use" statement for "ApiPlatform\Metadata\ResourceClassResolverInterface"?    
```


Feels like something is breaking inside during first call.

**Comment by soyuka** [comment] 2023-04-24 08:11
> The problem is in:
> https://github.com/api-platform/core/blob/main/src/Api/ResourceClassResolver.php#L28
> It implements ResourceClassResolverInterface but is missing a use statement, which should be:

No as `ApiPlatform\Api\ResourceClassResolverInterface` exists? I'll try to reproduce this this afternoon!

**Comment by dorantor** [comment] 2023-04-24 08:15
I can confirm what @frenci8 told. After I implemented workaround 
```json
{
...
    "require": {
...
        "api-platform/core": "3.1.7",
    }
}
```
everything is working smoothly again.

**Comment by Pierstoval** [comment] 2023-04-24 08:20
Just to add my 2cents, it also broke on my app boilerplate, just upgrading to 3.1.8 broke the app at container-compilation time: https://github.com/Pierstoval/php-js-boilerplate/actions/runs/4781180343/jobs/8499400355

All other dependencies are at their latest versions except 2 small ones:
![image](https://user-images.githubusercontent.com/3369266/233939805-c715d952-e23f-4f39-a966-b417eeb16f1c.png)

**Comment by soyuka** [comment] 2023-04-24 08:26
I'm on it ;) rollback to 3.1.7 for now

**Comment by soyuka** [comment] 2023-04-24 08:38
https://github.com/api-platform/core/compare/3.1...soyuka:core:3.1 can you try that ?

**Comment by Pierstoval** [comment] 2023-04-24 09:06
> [3.1...soyuka:core:3.1](https://github.com/api-platform/core/compare/3.1...soyuka:core:3.1) can you try that ?

![image](https://user-images.githubusercontent.com/3369266/233951173-83afb8c2-c27d-4b34-829b-fa505f7d4d06.png)

I'd like to yes 😅

**Comment by soyuka** [comment] 2023-04-24 09:08
just `dev-3.1`

**Comment by soyuka** [comment] 2023-04-24 09:17
tagged as 3.1.9 let me know if it still breaks

**Closed by soyuka** 2023-04-24 09:17 UTC
