### ISSUE TITLE
Error illegal string offset['direction'] on REST

### ISSUE THREAD

**Issue by BernardA** [api-platform/core#3395] opened 2020-02-09 14:44 UTC
**API Platform version(s) affected**: "api-platform/api-pack": "^1.2",

**Description**  
Throwing Ilegal string offset['direction'] when attempting to get items.

Note that this is happening with API-Platform/admin which uses REST.

**I am using GraphQl on most of my app and have not experienced any issue with pagination.**

**How to reproduce**  

1-This is the URI I am trying to reach `http://127.0.0.1:8000/api/ads?_order[id]=DESC&page=1&perPage=10`

2-Those are relevant excerpts from the Ad entity:

      * @ApiFilter(
      *     OrderFilter::class,
      *     properties={
      *         "createdAt"="DESC",
      *     },
      *     arguments={"orderParameterName"="_order"}
      * )

 ......

        * @ApiResource(
       *      attributes={
       *         "pagination_via_cursor"={"field"="createdAt", "direction"="DESC"}
       *      },

The error is thrown at `api-platform\/core\/src\/Hydra\/Serializer\/PartialCollectionViewNormalizer.php`, on the method `cursorPaginationFields`.

A dump of the $fields argument of the method above is:

      array(2) {
         ["field"]=>
              string(9) "createdAt"
         ["direction"]=>
            string(4) "DESC"
        }

The error is thrown at the function below. 

          foreach ($fields as $field) {
            $forwardRangeOperator = 'desc' === strtolower($field['direction']) ? 'lt' : 'gt';

So, apparently $fields should be an array of arrays, not a simple array. 

**Possible Solution**  

**Additional Context**

**Comment by soyuka** [comment] 2020-02-18 10:54
We should definitely sanitize this value and throw a better error if not fixing this behavior.

**Comment by teohhanhui** [comment] 2020-02-18 14:47
Duplicate of #3348

**Closed** 2020-02-21 14:27 UTC
Labels: duplicate

**Comment by BernardA** [comment] 2020-02-21 15:12
So, you mark as duplicate. Fine. And close it. Is there any actual solution?

**Comment by teohhanhui** [comment] 2020-02-21 15:26
Please see https://github.com/api-platform/core/issues/3348#issuecomment-583628403 for the correct solution. The documentation is wrong and needs to be fixed.

**Comment by Ayato-hub** [comment] 2022-10-11 12:57
> Please see [#3348 (comment)](https://github.com/api-platform/core/issues/3348#issuecomment-583628403) for the correct solution. The documentation is wrong and needs to be fixed.

Is this still up to date?
[#3348](https://github.com/api-platform/core/issues/3348)
Because I tryed

```
paginationViaCursor: [
        ['field' => 'timestamp', 'direction' => 'DESC']
    ]
```
and I get still get this error: `Object of class DateTime could not be converted to string`
and this dose not look like it would fit `"pagination_via_cursor"={"fields"={"field"="id", "direction"="DESC"}}`
