### ISSUE TITLE
Conflict with nelmio api documentation

### ISSUE THREAD

**Issue by Nek-** [api-platform/core#1757] opened 2018-03-08 15:34 UTC
Hello,

I tried to use nelmio api doc to document another endpoint not managed by api platform and it looks like it is... impossible. ApiPlatform override some parts of nelmio api docs and makes it unusable in another context.

Or maybe I'm missing some configuration?

I already tried the obvious:
```yaml
api_platform:
    enable_nelmio_api_doc: false
```

**Comment by Simperfit** [comment] 2018-04-09 08:37
If you look at how the extension is done, if you set this to false: 
```
// NelmioApiDoc support
        if (isset($bundles['NelmioApiDocBundle']) && $config['enable_nelmio_api_doc']) {
            $loader->load('nelmio_api_doc.xml');
        }
```
The xml declation file is not loaded and so, nothing is overriden.

Could you please give more insight on what is not working ?

**Comment by Nek-** [comment] 2018-04-09 16:47
I tested in a raw application. I can't get the same issue that I had previously.

But there's still another issue. Look at my custom doc (probably related), it contains the api platform doc !
![image](https://user-images.githubusercontent.com/972456/38510777-533a8294-3c26-11e8-984d-52998584ac25.png)

**Comment by Simperfit** [comment] 2018-04-24 11:03
could you please push that project ? So I can test and reproduce to find a fix ? 

Or do you want to work on a fix ?

Thanks ;).

**Comment by Nek-** [comment] 2018-04-24 17:56
Hello, here it is.
[test-nelmio-platform.zip](https://github.com/api-platform/core/files/1943969/test-nelmio-platform.zip)

**Comment by soyuka** [comment] 2019-04-07 10:00
@Nek- closing this because it looks like we're not recommending nelmio anymore in favor of Swagger, could you confirm that this is still an issue.

**Closed by soyuka** 2019-04-07 10:00 UTC
Labels: bug, unconfirmed

**Comment by Roadirsh** [comment] 2019-12-26 17:29
It is still an issue, do you still recommand using https://github.com/zircote/swagger-php ? @soyuka

**Comment by Nek-** [comment] 2019-12-26 22:44
@Roadirsh I recommend you to write a YAML file containing your documentation instead of annotations :wink: . swagger-php is losing time to me
