### ISSUE TITLE
REST pagination Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by BernardA** [api-platform/core#3406] opened 2020-02-21 08:49 UTC
**API Platform version(s) affected**: "api-platform/api-pack": "^1.2"

**Description**  
This is coming from `/api-platform/admin` when attempting to get initial info on entity through URL 
`/api/ads?order[id]=DESC&page=1&perPage=10`

Error is thrown at : `/api-platform\/core\/src\/Hydra\/Serializer\/PartialCollectionViewNormalizer.php","line":160`

A dump of the field variable on the method above will output:

     array(2) {
        ["field"]=>
            string(9) "createdAt"
        ["direction"]=>
            string(4) "DESC"
       }

This is related to [this issue](https://github.com/api-platform/core/issues/3395). 
I did change the annotation to temporarily solve that issue as below:

**Also note that I do not have any issues with the same pagination using GraphQl**

Relevant excerpts from the Ad entity:

       * @ApiFilter(
       *     OrderFilter::class,
       *     properties={
       *         "createdAt"="DESC",
       *     },
      *     arguments={"orderParameterName"="_order"}
      * )

       .....

         * @ApiResource(
        *      attributes={
        *         "pagination_via_cursor"={"field"="createdAt", "direction"="DESC"}
        *      },

I do have a `__toString` method in that entity:

     public function __toString(): string
    {
        return $this->description;
    }

**How to reproduce**  
To reproduce it, attempt to reach URL ``/api/ads?order[id]=DESC&page=1&perPage=10``.
Full code available at [this repo.](https://github.com/BernardA/quiamo-api) 

**Possible Solution**  

**Additional Context**

**Comment by teohhanhui** [comment] 2020-02-21 14:26
Sorry, I don't understand this issue. It seems like another duplicate of #3348 and #3395?

**Closed** 2020-02-21 14:27 UTC
Labels: duplicate

**Comment by BernardA** [comment] 2020-02-21 15:10
Great! You do not understand but you still close it. 
No, it's not a duplicate. As said, I 'hacked' the annotation to avoid problem 3348/3395. Then it goes on but throws this one error.

**Comment by ishapkin** [comment] 2022-12-14 21:40
In my case it error was because I'm used OnFlushEventArgs and forgot to set new field for my history trait
