### ISSUE TITLE
[HELP NEEDED] PUT is not updating an entity

### ISSUE THREAD

**Issue by Caaliitis** [api-platform/core#2155] opened 2018-08-12 23:05 UTC
I have composer up to date for everything. Using this on Symfony 4.
Tried to do update on one of the entities 
``````

/**
 * @ORM\Entity
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 * @ApiResource(
 *     collectionOperations={
 *          "post_comment"={
 *               "route_name" = "api_add_comment",
 *               "method" = "POST"
 *           },
 *     "get_single"={
 *               "route_name" = "api_get_comment",
 *               "method" = "GET",
 *           },
 *     "get_all"={
 *               "route_name" = "api_get_comments",
 *               "method" = "GET",
 *           },
 *     },
 * )
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment extends \FOS\CommentBundle\Entity\Comment implements SignedCommentInterface
{
``````

Sending `{"body":"test"}` to update the existing entity, but it returns old one with 200 OK status. No errors, no nothing. Happens to all of the entities. 
Any suggestions?

**Comment by sroze** [comment] 2018-08-13 06:46
Can you describe us how you send this HTTP request? With a reproducible
`curl` command for example?

**Comment by Caaliitis** [comment] 2018-08-13 06:49
I send {"body":"my text"} trough postman and content type as ld+json,
method put and URL 127.0.0.1:8000/api/comments/{commentId} in my case 1

**Comment by jonag** [comment] 2018-08-13 08:44
Since you have set the tracking policy of your entity to `@ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")` an explicit call to `persist()` need to be done on the entity manager in order to save the changes.

API Platform [don't call persist()](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Common/DataPersister.php#L54) if the entity is already managed, so I think that's why your changes are not saved in the database. Can you try to remove the `ChangeTrackingPolicy` on your entity to check if this fix your issue ?

**Comment by soyuka** [comment] 2018-10-03 08:51
Should be fixed by https://github.com/api-platform/core/pull/2226

**Closed by soyuka** 2018-10-03 08:51 UTC
