### ISSUE TITLE
Incorrect type resolved

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#3942] opened 2021-01-05 17:49 UTC
If you have a resource with:

```php
/**
 * @var string|float
 */
public $x;

public ?User $y;
```

The resolved types (for the schema) will be `string` for `$x` and `User` for `$y` which are both incorrect. I think a part of the problem is `PropertyMetadata` which accepts only one `Symfony\Component\PropertyInfo\Type` which wouldn't be incorrect if the later supported unions correctly (right now it simplifies flatten them, i.e. `string|float` -> `[type(string), type(float)]` which offers very limited possibilities for any complex type form: union, intersections, generics or nested structures). As a result in https://github.com/api-platform/core/blob/da500b2/src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyMetadataFactory.php only the first type is picked

**Comment by soyuka** [comment] 2021-02-23 15:02
duplicate of https://github.com/api-platform/core/issues/2503

**Closed by soyuka** 2021-02-23 15:02 UTC
