### ISSUE TITLE
Output class replaces input class in swagger after upgrade from 2.6.3 to 2.6.4

### ISSUE THREAD

**Issue by nightio** [api-platform/core#4257] opened 2021-04-28 11:23 UTC
**API Platform version(s) affected**: 2.6.4

**Description**  
If action has configured output class, it shows also as input in swagger

**How to reproduce**  
```php
# TokenRequest

#[ApiResource(
    collectionOperations: [
    'get_token' => [
        'output' => TokenResponse::class,
        'method' => 'POST',
        'path' => '/token',
        'controller' => CreateTokenController::class,
    ],
],
    itemOperations: [],
)]
class TokenRequest
{
    public ?string $a = null;
    public ?string $b = null;
}
```

```php
# TokenResponse

class TokenResponse
{
    public string $token;
}
```

**Additional Context**  
swagger UI on 2.6.3
![Screenshot 2021-04-28 at 13 15 59](https://user-images.githubusercontent.com/36849548/116395534-89419e00-a824-11eb-8fa9-603db18273e2.png)
swagger UI on 2.6.4
![Screenshot 2021-04-28 at 13 17 14](https://user-images.githubusercontent.com/36849548/116395726-c86fef00-a824-11eb-9873-1b2f3916be1c.png)

> Also changing media type on 2.6.4 does not change example output

**Comment by guilliamxavier** [comment] 2021-04-28 11:38
Duplicate of #4212 / #4215

**Comment by jsawicki-internetcompany** [comment] 2021-05-10 07:37
Similar to: https://github.com/api-platform/api-platform/issues/1899

**Closed** 2021-06-23 10:23 UTC
