### ISSUE TITLE
[Bug?] Inheritance doesn't work on @Groups since 2.4.4 as previously

### ISSUE THREAD

**Issue by ludovig** [api-platform/core#2876] opened 2019-06-25 09:33 UTC
Previously, an entity without ApiResource annotation, extending an entity with @ApiResource, could be nested. 
An example below. When I called from profiles/{id} get endpoint (class Profile) the $contentUrl of associated ProfileAvatarThumbnail was shown.

the parent src/Entity/ProfileAvatar : 
```php
/**
 * @ApiResource()
 */
class ProfileAvatar
{
    public $url; 
```
and children, a thumbnail of ProfileAvatar : 
```php
class ProfileAvatarThumbnail
{   
     /*
      * @Groups("profile")
     */
    public $url; 
```
Now to get it working, I needed to move Groups annotation to parent entity (ProfileAvatar), or to made children an ApiResource also. 

Is this an expected new behaviour or a bug ?

Thanks.

**Comment by remoteclient** [comment] 2019-06-25 13:30
Could that be related to [#2868](https://github.com/api-platform/core/issues/2868)?

**Comment by teohhanhui** [comment] 2019-07-05 18:35
It's not a bug. We should not leak information from child classes that are not an API resource.

**Comment by teohhanhui** [comment] 2019-07-05 18:38
Hmm... Okay, I didn't read properly. So it's the same property already in the parent. Looks like a bug then.

**Comment by teohhanhui** [comment] 2019-07-18 16:36
Looking back at this, I'm not sure if this is a bug. It actually sounds like the current behaviour is correct.

Would you expect additional properties from the children of an API resource class? I think we should not leak information from child classes that are not marked as API resource classes.

**Comment by teohhanhui** [comment] 2019-07-18 16:38
@ludovig In your case, you could already set the serializer group on the property of the parent class, by using YAML or XML mapping. And that seems like the correct thing to do when dealing with inheritance.

**Closed** 2021-02-19 10:38 UTC
Labels: invalid, waiting
