### ISSUE TITLE
Swagger doc normalizer does not handle definitions correctly 

### ISSUE THREAD

**Issue by aistis-** [api-platform/core#1031] opened 2017-04-05 11:16 UTC
Hi!

I am trying to define custom swagger docs, definitions are not parsed correctly. For example: If I have only one custom endpoint for resource (`PUT`), and I define in `swagger_context` fields [parameters](https://github.com/api-platform/core/blob/aaae07f3f6c012388372383f6b707fd58cf66720/src/Swagger/Serializer/DocumentationNormalizer.php#L296) and [responses](https://github.com/api-platform/core/blob/aaae07f3f6c012388372383f6b707fd58cf66720/src/Swagger/Serializer/DocumentationNormalizer.php#L310), [getDefinition](https://github.com/api-platform/core/blob/aaae07f3f6c012388372383f6b707fd58cf66720/src/Swagger/Serializer/DocumentationNormalizer.php#L356) never will be called, so definition will not be generated to swagger dump also!

**Comment by dunglas** [comment] 2017-04-06 07:26
Can you provide some failing code?

**Comment by aistis-** [comment] 2017-04-06 07:34
Let's say we have only one endpoint in the entire application. It is defined as custom endpoint (`_api_receive: false`).

```
resources:
    My\Bundle\ApiBundle\Model\Category:
        collectionOperations:
            put:
                route_name: api_category_put
                swagger_context:
                    summary: Replaces all existing categories by new array of categories.
                    consumes:
                        - application/json
                    parameters:
                        -
                            name: body
                            in: body
                            schema:
                                $ref: '#/definitions/Category'
                    definitions:
                        Category:
                            type: string
                            required:
                                - id
                            schema:
                                id:
                                    type: string
                                parent_id:
                                    type: string
                    responses:
                        200:
                            description: Operations successful.
                        400:
                            description: Bad request (failed validation).
        itemOperations: []
```

**Comment by Perf** [comment] 2018-04-25 09:32
I'm having the same issue, `$ref` is never resolved.
```
resources:
    App\Entity\SocialLogin:
# ...
        collectionOperations:
# ...
            check:
# ...
                swagger_context:
# ...
                    responses:
                        200:
                            description: "Successful authentication with OAuth2 provider, returning new token"
                            schema:
                                $ref: '#/definitions/Token'
                        201:
                            description: "New user account has been created and confirmed, returning new token"
                            schema:
                                $ref: '#/definitions/Token'
                        401:
                            description: "Connection with existing user's account is not confirmed or was disabled"
definitions:
    Token:
        type: object
        properties:
            token:
                type: string
                description: "JWT authentication token"
```
Responses has only descriptions, without definitions
<img width="1332" alt="screen shot 2018-04-25 at 11 30 41" src="https://user-images.githubusercontent.com/42077/39237582-3c322284-487c-11e8-932d-53a674da47d0.png">

**Comment by Simperfit** [comment] 2018-05-03 11:39
Could you please provide a little project to reproduce this issue ?

**Comment by Perf** [comment] 2018-05-03 11:46
@Simperfit 
just put somewhere in resources yaml file root section with definitions and `$ref:` at place where this definition should be shown - in my example I tried to show definition in Response section - and it is not shown. Please take a look at my example above.

**Comment by alinepure** [comment] 2018-08-13 13:58
Same issue here too. If you define a 'swagger_definition_name' for a (de)normalization_context and try to use it as $ref in 'parameters' or 'responses' sections won't work.

### Case 1: don't  overwrite the parameters or responses sections. 


```
resources:
    App\Entity\User:
        normalizationContext: {groups: ['read']}
        denormalizationContext: {groups: ['write']}
        itemOperations:
            get: ~
            delete: ~
            put: ~
            login:
                method: 'POST'
                path: '/auth'
                controller: 'App\Controller\AuthController'
                normalization_context: {groups: ['get_token'], swagger_definition_name: 'GetToken'}
                denormalization_context: {groups: ['login'], swagger_definition_name: 'Login'}
                swagger_context:
                    summary: Generates user access token.
                    description: >
                        General description
        collectionOperations:
            get: ~
            post: ~
```

Result:

<img width="1354" alt="screen shot 2018-08-13 at 16 38 00" src="https://user-images.githubusercontent.com/629525/44035515-5e354bf2-9f18-11e8-8356-87c4170f4c12.png">

<img width="1343" alt="screen shot 2018-08-13 at 16 38 15" src="https://user-images.githubusercontent.com/629525/44035535-6784202a-9f18-11e8-8c4e-b61f903b54d1.png">

<img width="589" alt="screen shot 2018-08-13 at 16 44 17" src="https://user-images.githubusercontent.com/629525/44035563-73eadbba-9f18-11e8-9043-676f9c8ccb0f.png">


### Case 2: overwrite the parameters and responses sections to display the correct name/code and description

```
resources:
    App\Entity\User:
        normalizationContext: {groups: ['read']}
        denormalizationContext: {groups: ['write']}
        itemOperations:
            get: ~
            delete: ~
            put: ~
            login:
                method: 'POST'
                path: '/auth'
                controller: 'App\Controller\AuthController'
                normalization_context: {groups: ['get_token'], swagger_definition_name: 'GetToken'}
                denormalization_context: {groups: ['login'], swagger_definition_name: 'Login'}
                swagger_context:
                    summary: Generates user access token.
                    description: >
                        General description
                    parameters:
                        - in: body
                          name: credentials
                          required: true
                          schema:
                            $ref: '#/definitions/User-Login'
                          description: The account username and password
                    responses:
                        '200':
                            description: User access token generated
                            schema:
                                $ref: '#/definitions/User-GetToken' 
                        '401':
                            description: 'Bad credentials'
                        '404':
                            description: 'Resource not found'
        collectionOperations:
            get: ~
            post: ~
```

Result:

<img width="1345" alt="screen shot 2018-08-13 at 16 50 12" src="https://user-images.githubusercontent.com/629525/44035898-36c2873c-9f19-11e8-846a-5fa428ed0a76.png">

<img width="1336" alt="screen shot 2018-08-13 at 16 50 24" src="https://user-images.githubusercontent.com/629525/44035981-62c6e670-9f19-11e8-84cc-3a679cc1aac4.png">

<img width="378" alt="screen shot 2018-08-13 at 16 50 34" src="https://user-images.githubusercontent.com/629525/44036174-da582fe6-9f19-11e8-9e87-4c929d9e9f4a.png">

**Comment by trsteel88** [comment] 2018-08-17 12:27
Did anyone work this one out? Having the same trouble.

**Comment by Cethy** [comment] 2018-10-15 15:59
I believe to have the same trouble ;

When you use custom `swagger_definition_name`, the `DocumentationNormalizer` will be confused when trying to build resources definitions, especially for sub/children resources :

Let say I have :
```
/**
 * @ORM\Entity
 *
 * @ApiResource(
 *     collectionOperations={"get"={
 *          "normalization_context"={"groups"={"foo","bar"}, 
             "swagger_definition_name"="list"}
 *     }}
 * )
 */
class Parent {
  /**
   * @var Child
   */
    private $child;

    // ...
}

/**
 * @ORM\Entity
 *
 * @ApiResource(
 *     collectionOperations={"get"={
 *          "normalization_context"={"groups"={"foo","bar"}, 
             "swagger_definition_name"="read"}
 *     }}
 * )
 */
class Child {}
```

In `DocumentationNormalizer::l389`, when looking for/generate the `child` attribute definition, it will look for a `swagger_definition_name` = `Child-list` (entityName+swagger def name), and break because none exists (or generate something broken anyway).

I believe the autogen definitionKey should be kept until the end of the doc normalization process where the custom names should be set.

**Comment by Cethy** [comment] 2018-10-15 23:16
@trsteel88, I ended taking my own advice :
I removed all `swagger_definition_name` & in a `SwaggerDecorator` I added a correspondence table between the autogenerated def names & the ones I wanted to use.

Quick & dirty example : 
```
public function normalize($object, $format = null, array $context = array())
{
    /** @var Documentation $docs */
    $docs = $this->decorated->normalize($object, $format, $context);

    // change definitions names
    $docStr = json_encode($docs);
    foreach(self::CUSTOM_DEF_NAMES as $oldDefName => $newDefName) {
        $docStr = str_replace('"#\/definitions\/'. $oldDefName .'"', '"#\/definitions\/'. $newDefName .'"', $docStr);
        $docStr = str_replace('"'. $oldDefName .'"', '"'. $newDefName .'"', $docStr);
    }
    $docs = json_decode($docStr, true);
}
```

Hope this helps!

**Comment by soyuka** [comment] 2019-04-06 15:28
Closing this as it seems to be resolved.

**Closed by soyuka** 2019-04-06 15:28 UTC
Labels: bug, unconfirmed
