### ISSUE TITLE
error while activating graphql on Api-Platform from symfony

### ISSUE THREAD

**Issue by akilshadi** [api-platform/core#3652] opened 2020-07-22 15:26 UTC
I try to activate GraphQL Support on symfony api-platform, but when i visit folloing route, i got error:

/api/graphql

the error message is:
`Attempted to load class "Debug" from namespace "GraphQL\Error".
Did you forget a "use" statement for e.g. "Symfony\Component\ErrorHandler\Debug" or "Doctrine\Common\Util\Debug"?`

**Comment by alanpoulain** [comment] 2020-07-22 15:27
Fixed by https://github.com/api-platform/core/pull/3621.
You need to either:
- wait for a new version to be released
- use the dev version of the `2.5` branch
- downgrade webonyx/graphql-php to a previous version (`0.13`)

**Closed by alanpoulain** 2020-07-22 15:27 UTC

**Comment by akilshadi** [comment] 2020-07-23 08:10
the second solution did not work for me:
i tried to install dev-master / 2.6.x-dev but did not work
is that right?
`composer require api-platform/core:dev-master `

**Comment by alanpoulain** [comment] 2020-07-23 08:24
It's not `dev-master`, it's `dev-2.5`.

**Comment by mischabraam** [comment] 2020-08-13 06:11
Referring to a `dev-xx` branch of some sort doesn't look like the issue is resolved to me. Clean installation with `composer require ..` and it doesn't work. Why is this issues closed, while the bug itself is not in the latest release (2.5.6)?

**Comment by mischabraam** [comment] 2020-08-13 06:27
@akilshadi you can use `composer require cweagans/composer-patches` and the following patch.

```
--- /vendor/api-platform/core/src/GraphQl/Action/EntrypointAction.php	2020-08-13 08:22:33.000000000 +0200
+++ /vendor/api-platform/core/src/GraphQl/Action/EntrypointAction.php	2020-08-13 08:21:56.000000000 +0200
@@ -15,7 +15,7 @@

 use ApiPlatform\Core\GraphQl\ExecutorInterface;
 use ApiPlatform\Core\GraphQl\Type\SchemaBuilderInterface;
-use GraphQL\Error\Debug;
+use GraphQL\Error\DebugFlag as Debug;
 use GraphQL\Error\Error;
 use GraphQL\Error\UserError;
 use GraphQL\Executor\ExecutionResult;
```
