### ISSUE TITLE
Associations initialized as array instead of ArrayCollection

### ISSUE THREAD

**Issue by felicitus** [api-platform/core#152] opened 2015-07-04 23:45 UTC
I'm trying to implement an event listener as per [documentation](https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/the-event-system.md#registering-an-event-listener). The Doctrine documentation states that associations should be initialized, and they use an [ArrayCollection](http://www.doctrine-project.org/api/common/2.1/class-Doctrine.Common.Collections.ArrayCollection.html) as default. In my project, this is exactly the same, and I expect that the return value of my getter is always of the `ArrayCollection` class.

It seems that `DunglasAPIBundle` deserializes associations as `array`, not as `ArrayCollection`. Thus I can't use the `ArrayCollection´ methods in the event listener, because a call to my getter returns an `array` instead of an `ArrayCollection`.

**Comment by felicitus** [comment] 2015-07-05 00:01
Clarification: What I'm trying to achieve is to add or remove entities from the collection after deserializing.

**Comment by dunglas** [comment] 2015-07-05 08:12
Does your entity have a setter or only adder/remover? As a workaround I think that the PropertyAccess component will not override the default type when using adder/remover method.

Another workaround is to test the type of the parameter is the setter and to instatiate an ArrayCollection from the array.

**Comment by felicitus** [comment] 2015-07-05 22:47
I have a setter, so in theory, this should work fine.

I debugged a bit further, here are my findings:

In putAction, directly after `$object = $this->findOrThrowNotFound($resource, $id);`, when I call the getter, I receive an object of type `PersistentCollection`. This indicates that the object loaded from the database has items persisted to the database. From reading the API docs for the [PersistentCollection](http://www.doctrine-project.org/api/orm/2.1/class-Doctrine.ORM.PersistentCollection.html) it seems that this is absolutely required in order to add/remove child associations if the entity has already been persisted to the database.

As soon as the deserializer steps into action, it will silently overwrite the `PersistentCollection` with the array data passed as JSON, instead of using the existing collection to add/remove child entities as required.

**Comment by dunglas** [comment] 2015-07-06 11:38
I'll investigate about that. Does it works if you comment the setter but letter the adder and the remover?

**Comment by felicitus** [comment] 2015-07-06 16:47
No, I receive an error that no setter is configured. I guess this issue is related to #153.

**Comment by dunglas** [comment] 2015-07-07 06:41
The problem is related to Doctrine internals. I've opened a PR on PartKeepr with a workaround: partkeepr/PartKeepr#409. Let me know if you think it's OK to close this bug.

**Closed** 2016-08-19 22:45 UTC
Labels: question
