### ISSUE TITLE
Deserialization doesn't work for embedded objects

### ISSUE THREAD

**Issue by magarzon** [api-platform/core#942] opened 2017-02-13 12:42 UTC
If I have an API Resource that has a field that is an object of certain class, the deserialization process doesn't call the normalizer for this class (if set), and returns an array of values for this field.

For example, I have an API Resource that has a field "mobile" of class PhoneNumber.
I want to deserialize this:
```
{"mobile":{"country_code":"34", "number":"666666666"}}
```

The problem is that the Symfony serializer use a propertyTypeExtractor to guess the type of a field. This extractor can be set if you use directly the ObjectNormalizer, passing it in the constructor. Also, it's set automatically for the serializer service in Symfony if the Property Info Component is enabled, using the PHPDocExtractor.

This extractor is set in Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer, that is extended by ApiPlatform\Core\Serializer\AbstractObjectNormalizer and this extended by ItemNormalizer, that is the normalizer used for API Resources, but that calls to the parent constructor with this extractor parameter set to null.

**Comment by dunglas** [comment] 2017-02-13 13:40
API Platform has its own extraction system for resources (relying on the metadata system). For non-resources, the serialization is delegated to Symfony's `ObjectNormalizer`. Can you provide a test to reproduce the problem?

**Comment by magarzon** [comment] 2017-02-14 11:33
It's weird, seems to be working today, probably cache issues. Anyway, I'll try to create a test for this, so we have it controlled.

**Comment by Simperfit** [comment] 2017-06-08 12:43
@magarzon can we close this ?

**Comment by magarzon** [comment] 2017-06-09 11:10
Yes

**Closed** 2017-06-09 16:11 UTC
Labels: bug, unconfirmed

**Comment by dberniell** [comment] 2019-04-21 16:44
How did you solve this? If I have getter and setter method in parent embedded property I get "Invalid value". The embedded property isn't decoded. If I remove getter and setters I get null values on embedded property, because property isn't deserialized as an allowed attribute. Don't know how to work with @ORM\Embedded and @ORM\Embeddable, but I'd like to use it. Before updating api-platform/core to 2.4.2 it worked.

**Comment by teohhanhui** [comment] 2019-04-23 20:20
@dberniell This issue is very old and unrelated to your problem. Please open a separate issue if it's still broken with the latest `2.4` branch (`2.4.x-dev` for composer).
