### ISSUE TITLE
Bad Content-Type after DELETE operation

### ISSUE THREAD

**Issue by fmata** [api-platform/core#949] opened 2017-02-16 16:43 UTC
Hi,

When I do a DELETE /api/foo/1, the response code is 204 with no content but the Content-Type header is always "text/html; charset=UTF-8" even I set jsonld as default format or I set an Accept header to "application/ld+json".

Is it the normal behaviour ? I consider it as a bug.

In a generic Hydra client which tries to follow norms, this behaviour breaks the process of a response which is based on Content-Type.

Thank you.

**Comment by dunglas** [comment] 2017-02-16 17:02
It can be considered as a bug, and it's an easy pick :)

**Comment by fmata** [comment] 2017-02-17 15:02
I try to fix.

ApiPlatform\Core\EventListener\RespondListener sets the right Content-Type but Symfony removes it in ResponseListener.php:49 but I can not find where the Content-Type is set to "text/html"...

I tried in dev/prod env with Postman and PHPStorm RESTful client and I always get a bad Content-Type.

Can you reproduce ?

No Content-Type at all or the right one is ok for me, but not a false :(

**Comment by dunglas** [comment] 2017-02-18 09:54
No content type is better because if we set the content type as JSON, the response must contain a valid JSON document and it's not actually the case.

**Comment by soyuka** [comment] 2017-02-24 14:10
In fact the symfony Response does remove the Content-Type [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L270) when status is 204. We shouldn't have to fix this, but I can confirm that the Content-Type is defaulted to `text/html` somehow but I can not find where it's being set either :|.

**Comment by teohhanhui** [comment] 2017-02-27 05:01
See symfony/symfony#12744, symfony/symfony#11244 and https://bugs.php.net/bug.php?id=70189

This is out of our hands.

**Comment by dunglas** [comment] 2017-02-27 07:18
It seems to have been fixed in PHP. Maybe should we set ˋdefault_mimetype` to empty on our Docker setup and some doc about how to configure properly in production.

**Comment by teohhanhui** [comment] 2017-02-27 10:40
I think
```php
ini_set('default_mimetype', '');
```
should work.

See e.g. slimphp/Slim#1690 and slimphp/Slim#1629

This should be fixed in Symfony.

**Comment by teohhanhui** [comment] 2017-02-27 10:48
Opened symfony/symfony#21778

**Comment by teohhanhui** [comment] 2019-07-11 13:07
This is still an issue. Will look into it again.

**Closed** 2019-07-11 13:21 UTC
Labels: bug
