### ISSUE TITLE
Change API Platform priorities

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#2357] opened 2018-12-01 13:11 UTC
With the rise of autowiring, user provided normalizers must be called before API Platform ones. It's currently not the case, and you have to set a custom priority, it hurts DX.

Current priorities:

* ApiPlatform\Core\Hydra\Serializer\ConstraintViolationListNormalizer
* ApiPlatform\Core\Hydra\Serializer\DocumentationNormalizer
* ApiPlatform\Core\Hydra\Serializer\EntrypointNormalizer
* ApiPlatform\Core\Hydra\Serializer\ErrorNormalizer
* ApiPlatform\Core\Swagger\Serializer\ApiGatewayNormalizer
* ApiPlatform\Core\Swagger\Serializer\ApiGatewayNormalizer
* ApiPlatform\Core\Hydra\Serializer\CollectionFiltersNormalizer
* ApiPlatform\Core\Problem\Serializer\ConstraintViolationListNormalizer
* ApiPlatform\Core\JsonLd\Serializer\ItemNormalizer
* ApiPlatform\Core\Problem\Serializer\ErrorNormalizer
* ApiPlatform\Core\GraphQl\Serializer\ItemNormalizer
* **App\Serializer\ReactionCollectionNormalizer** <-- autowired normlaizer is here
* ApiPlatform\Core\Serializer\ItemNormalizer
* Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer
* Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
* Symfony\Component\Serializer\Normalizer\ConstraintViolationListNormalizer
* Symfony\Component\Serializer\Normalizer\DateIntervalNormalizer
* Symfony\Component\Serializer\Normalizer\DataUriNormalizer
* Symfony\Component\Serializer\Normalizer\ArrayDenormalizer
* Symfony\Component\Serializer\Normalizer\ObjectNormalizer

Related: #2315

**Comment by Taluu** [comment] 2018-12-01 22:15
There's also #1815 that can be related, but it's not only normalizers.

**Comment by teohhanhui** [comment] 2018-12-19 15:15
Not a bug.

**Comment by dunglas** [comment] 2018-12-19 15:37
It is. For 3.0?

**Comment by wimme002** [comment] 2019-01-07 12:38
Upgrading Symfony to 4.2.2 changes the order of the dataproviders and can break an application.

providers in ChainCollectionDataProvider on Symfony 4.2.2
- "ApiPlatform\Core\Bridge\Doctrine\Orm\CollectionDataProvider"
- "App\DataProvider\MyProvider"

providers in ChainCollectionDataProvider on Symfony 4.2.1
- "App\DataProvider\MyProvider"
- "ApiPlatform\Core\Bridge\Doctrine\Orm\CollectionDataProvider"

This means that the only way to use a custom Provider is to manually define it in services.yaml with a priority > 0

**Comment by olivermack** [comment] 2019-01-08 18:51
@wimme002 thanks for your note - I actually ran in exactly this issue ;).

**Comment by dunglas** [comment] 2019-01-08 22:49
This "non-bug" is affecting many users... Maybe should we do something before 3.0, even if it's a potential BC break, it will be more reliable and less confusing.

**Comment by antograssiot** [comment] 2019-01-09 13:09
I think it is worth it

**Comment by deguif** [comment] 2019-01-10 17:12
This seems related to https://github.com/symfony/symfony/issues/29836

**Comment by dunglas** [comment] 2019-01-10 18:22
It's not a "bug" because these priorities have been defined before the introduction of autoconfiguration in Symfony. However now that it's broadly used, it's very annoying.

The only issue with changing this, it's that a BC break that will definitely affect existing users. Anwyay, this bug in Symfony is maybe the opportunity to move forward?

@apfelbox negative priorities would indeed be the best solution! PRs welcome guys :)

**Comment by juhulee** [comment] 2019-01-15 10:37
hey, having the same problem.. do you have any example how to change the priority? 
I tried the default stuff in services.yaml.. 
` ############################################
    # EVENT LISTENERS + SUBSCRIBERS
    ############################################

    # we need to overwrite the blamable listener definition in order to adjust its priority
    # the default priority is 0 and thus it does not add the updatedBy before creating a logEntry
    stof_doctrine_extensions.event_listener.blame:
        class: "%stof_doctrine_extensions.event_listener.blame.class%"
        arguments:
            - "@stof_doctrine_extensions.listener.blameable"
            - "@security.token_storage"
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_subscriber, priority: -1 }
`

no difference, the error still occures..
Thanks, 
Julia

**Comment by juhulee** [comment] 2019-01-15 12:41
hmm but I just saw, that the PR has been reverted and already merged to symfony 3.4
waiting for 4.2 ;) 
https://github.com/symfony/symfony/pull/29853

**Comment by apfelbox** [comment] 2019-01-15 12:50
@juhulee I am not a user of the API platform myself, but if I understand it correctly your own listener needs to be added *before* the core listeners. So you need to use a priority **larger** than zero.

**Comment by soyuka** [comment] 2019-04-07 09:35
That's done in 2.4, changes have been logged in the changelog!

**Closed by soyuka** 2019-04-07 09:35 UTC
Labels: enhancement
