### ISSUE TITLE
Class elf does not exist

### ISSUE THREAD

**Issue by gharlan** [api-platform/core#3344] opened 2020-01-15 13:53 UTC
**API Platform version(s) affected**: 2.5.4 (2.5.3 is not affected)

**Description** / **How to reproduce**  
When using this property in an ApiResource

```php
    /**
     * @var self
     */
    public $foo;
```

.. I get the error "Class elf does not exist" on api docs.

**Additional Context**  

<img width="803" alt="Screenshot 2020-01-15 14 52 23" src="https://user-images.githubusercontent.com/330436/72439144-a6c13480-37a6-11ea-9b19-7eca9e4f4ad9.png">

**Comment by soyuka** [comment] 2020-01-20 14:43
could you try replacing `self` by `ClassName`?

**Comment by gharlan** [comment] 2020-01-20 14:59
> could you try replacing `self` by `ClassName`?

It seems to work. 
(I get another error then, from a different place: "Class App\Entity\UuidInterface does not exist")

With api-platform 2.5.3 there is no problem with `self` and `UuidInterface`.

**Comment by soyuka** [comment] 2020-01-20 15:35
`self` worked in my reproduction: https://github.com/soyuka/self-referencing-metadata-api-platform

see https://github.com/api-platform/core/pull/3350  these class FQDN do not exist.

**Comment by gharlan** [comment] 2020-01-20 15:49
> `self` worked in my reproduction: https://github.com/soyuka/self-referencing-metadata-api-platform

Checked out your repo, composer install, opened `/api` in browser -> "Class elf does not exist"
PHP 7.4

**Comment by gharlan** [comment] 2020-01-20 15:56
> Checked out your repo, composer install, opened `/api` in browser -> "Class elf does not exist"
> PHP 7.4

changed `self` to `Dummy` -> "Class App\Entity\EventDispatcherInterface does not exist"

**Comment by gharlan** [comment] 2020-01-20 15:57
The second problem seems to be related to traits. `EventDispatcherInterface` is used in a trait, and also `UuidInterface` in my project.

**Comment by soyuka** [comment] 2020-01-20 16:18
I tracked your issue to PhpDocumentor, I'll try to find a fast resolution, in the meantime please use a FQDN:

```diff
@var self
@var Dummy
```

Let's continue this discussion in https://github.com/api-platform/core/issues/3349

**Comment by gharlan** [comment] 2020-03-04 10:51
https://github.com/phpDocumentor/phpDocumentor/issues/2212

@soyuka So, do I understand correctly, that it is a bug in symfony/property-info?

**Comment by teohhanhui** [comment] 2020-03-04 11:19
Yes.

**Comment by gharlan** [comment] 2020-03-04 11:23
Thanks, but is it really related to the `self`/`elf` issue?

**Comment by teohhanhui** [comment] 2020-03-04 14:15
Oh, sorry, seems like there's no Symfony issue on that yet? /cc @soyuka

**Comment by soyuka** [comment] 2020-03-04 14:44
yes: https://github.com/symfony/symfony/issues/28732

**Comment by teohhanhui** [comment] 2020-03-04 15:31
@soyuka That's a different issue.

**Comment by teohhanhui** [comment] 2020-03-04 15:31
So indeed this issue is not a duplicate of #3349.

**Comment by silverbackdan** [comment] 2020-06-08 13:41
I have traced it to here (as I think was done in PHPDocumentor issue as well)
https://github.com/symfony/property-info/blob/0da4315bc563d9aaff7acb8bc72733bd433b33e9/Util/PhpDocTypeHelper.php#L163

This function looks as though it should be trimming the first `\` from an object class name. `self` would still be an object and looks like it'd have the same issue with `static` which I've seen may be introduced in PHP 8. I couldn't see an issue or PR in the Symfony repo, so I'll raise one and I'm sure if it's a duplicate and I've missed further discussion I'll be pointed in the right direction.

**Comment by silverbackdan** [comment] 2020-06-08 14:32
In my case, I am adding an object to an API resource/object in a data transformer. This object has a property referencing `Symfony\Component\PropertyAccess\PropertyPathInterface\FormInterface` which has annotations `@return self` but more importantly (I think) a method `setParent` which has an argument type set to `self`. Instead of typing `FormInterface` I am now instead type hinting to `Symfony\Component\Form\Form` and this object explicitly defines itself as the setter argument. It implements the same interface... and I think the fact it's an interface and possibly the type inheritance which could have something to do with this specific bug. I have other API resources type hinting `self` which do not throw any errors.

**Comment by byhaskell** [comment] 2021-12-02 15:22
Faced a similar problem, namely the error text: Class self does not exist
I added an ApiResource to the entity, but did not register the display groups, which is why there was an error. Perhaps this will help someone too!

**Closed** 2023-10-17 09:06 UTC
Labels: bug
