### ISSUE TITLE
DateFilter does not work properly for date without time in SQLite

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#581] opened 2016-06-22 08:06 UTC
Hi,

I'm implementing [DateFilter](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/DateFilter.php) on my project on a entity using a date (without time). In my tests, I have 3 objects with following dates: `2016-06-22`, `2016-06-23` & `2016-06-24`. When I search for objects with date after `2016-06-24` (so with `date >= 2016-06-24`), no objects are returned, instead of 1 (the last one).

On [DateFilter class line 152](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/DateFilter.php#L152), if I replace `new \DateTime($value)` with `$value`, it works well if value is a date with no time, but does not work anymore with a date with a time.

**Comment by soyuka** [comment] 2016-06-22 13:07
#482 related

**Comment by vincentchalamon** [comment] 2016-06-22 13:30
@soyuka It's not about output, it's about filter DQL query

**Comment by soyuka** [comment] 2016-06-22 13:43
Isn't this related to the normalizer?
Le mer. 22 juin 2016 à 15:31, Vincent CHALAMON <notifications@github.com> a
écrit :

**Comment by vincentchalamon** [comment] 2016-06-22 13:45
No cause this filter is executed before the normalization. But I agree, there is also another issue about date normalization 😉

**Comment by soyuka** [comment] 2016-06-22 14:18
Could you give an sql table schema? (what date type?) Or maybe the failing entity substract? Also, a data set to work with, thx!

Then I might be able to add a behat test and probably a fix. I'm trying to see where it could be broken, because with doctrine the comparison should work in collaboration with your column type, and so should work with or without time. If you work with a DateTime type it might just be the way it works and we maybe won't be able to fix this.

**Comment by teohhanhui** [comment] 2016-06-23 08:45
http://php.net/manual/en/datetime.createfromformat.php

| format character | Description | Example parsable values |
|---|---|---|
| \| | Resets all fields (year, month, day, hour, minute, second, fraction and timzone information) to the Unix Epoch if they have not been parsed yet | Y-m-d\| will set the year, month and day to the information found in the string to parse, and sets the hour, minute and second to 0. |

**Comment by teohhanhui** [comment] 2016-06-23 08:57
Initially I thought the problem is with `DateTime::__construct` but apparently not.

```php
new \DateTime('2016-06-23');
// object(DateTime) { ["date"] => "2016-06-23 00:00:00.000000" }
```

Are you using Doctrine's "date" type for that column? :smile:

**Comment by teohhanhui** [comment] 2016-06-23 10:24
@vincentchalamon "This invitation is invalid."

**Comment by soyuka** [comment] 2016-06-23 10:28
I was invited, can't check it out until this evening though.

**Comment by vincentchalamon** [comment] 2016-06-23 10:28
@teohhanhui GitHub requires me to "buy a new seat"… Can you give me your mail? So I'll be able to send you the code gzipped 😉

**Comment by teohhanhui** [comment] 2016-06-23 10:45
@vincentchalamon It's on my profile :wink:

**Comment by teohhanhui** [comment] 2016-06-23 12:09
It's actually a Doctrine bug when used with SQLite:

doctrine/doctrine2#4524
doctrine/doctrine2#1383

**Comment by vincentchalamon** [comment] 2016-06-23 12:10
Thanks @teohhanhui

**Comment by soyuka** [comment] 2016-06-23 14:01
thx @teohhanhui, good to know! I thought this was weird if not related with a specific database vendor because it works to me ^^.

**Comment by dunglas** [comment] 2016-06-25 13:48
Closing as this is a Doctrine bug.

**Closed by dunglas** 2016-06-25 13:48 UTC
Labels: bug

**Comment by teohhanhui** [comment] 2016-06-27 04:59
@dunglas We may want to work around this... Fat chance that the Doctrine bug will be fixed...

**Comment by dunglas** [comment] 2016-06-27 05:29
I'm -1 to workaround so specific Doctrine bugs in this repository. It should be fixed directly upstream or the workaround should be applied in the user app directly.

**Comment by teohhanhui** [comment] 2016-06-27 05:32
In that case, I'd suggest we add a test to trigger this bug. So we can see if it's possible to work around this bug in the test app...

**Comment by dunglas** [comment] 2016-06-27 05:51
👍 for this solution.
