### ISSUE TITLE
Configure router in AddLinkHeaderListener

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#3257] opened 2019-11-14 15:31 UTC
**API Platform version(s) affected**: 2.*

Original issue: https://github.com/nelmio/NelmioCorsBundle/issues/115

Discussion: https://github.com/nelmio/NelmioCorsBundle/pull/125#issuecomment-553864425

Solution: we should handle the router context in the AddLinkHeaderListener to fix the original issue

**Comment by dunglas** [comment] 2019-11-14 18:53
I don’t think we should introduce such logic in API Platform to prevent a side-effect caused by a third party library. The problem should be fixed in NelmioCors (and it can affect other libraries).

**Comment by teohhanhui** [comment] 2019-11-14 19:11
Doesn't https://github.com/nelmio/NelmioCorsBundle/pull/125#issuecomment-553848344 solve the problem?

**Comment by vincentchalamon** [comment] 2019-11-14 19:52
Already discussed [here](https://github.com/nelmio/NelmioCorsBundle/pull/125): the fix proposal in NelmioCors was refused. Everybody argued that it should be fixed on ApiPlatform...

**Comment by teohhanhui** [comment] 2019-11-14 20:01
I didn't find any explicit response to the fix you suggested, but anyway, I'd say it's wrong for `CorsListener` to break the request context on every `OPTIONS` request. `OPTIONS` is an important HTTP verb (I mean, all HTTP verbs are important lol :see_no_evil:), it's not only used for CORS preflight requests.

**Comment by soyuka** [comment] 2019-11-15 10:16
fixed by https://github.com/api-platform/core/pull/3265

**Closed** 2019-12-18 21:12 UTC
Labels: bug
