### ISSUE TITLE
Name converter is not working for sorting

### ISSUE THREAD

**Issue by slebrequier** [api-platform/core#2117] opened 2018-07-20 09:11 UTC
I am currently trying to use snake_case in my new webservices but sort (through OrderFilter) doesn't take snake_cased property names but PHP attribute ones.

Neither : 
```
/**
 * This is a dummy entity. Remove it!
 *
 * @ApiResource
 * @ORM\Entity
 * @ApiFilter(OrderFilter::class, properties={"idGreeting", "name"}, arguments={"orderParameterName"="order"})
 */
class Greeting
{
    /**
     * @var int The entity Id
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", name="id")
     */
    private $idGreeting;

    /**
     * @var string A nice person
     *
     * @ORM\Column
     * @Assert\NotBlank
     */
    public $name = '';

    public function getIdGreeting(): int
    {
        return $this->idGreeting;
    }
}
```

Nor : 
```
...
 * @ApiFilter(OrderFilter::class, properties={"id_greeting", "name"}, arguments={"orderParameterName"="order"})
...
```

Allow me to do : `http://localhost:8080/greetings?order[id_greeting]=desc`.

The only way I can sort is by using `idGreeting` in both annotation and query parameter.

Is it possible to have the same naming conversion in the request body, the response body and then query parameters?
Otherwise I will have to use camelCase :(.

**Comment by teohhanhui** [comment] 2018-07-20 09:44
Duplicate of https://github.com/api-platform/core/issues/2090

**Closed by teohhanhui** 2018-07-20 09:44 UTC
