### ISSUE TITLE
Swagger Look Messy with Subresource

### ISSUE THREAD

**Issue by bitcoinporn** [api-platform/core#1316] opened 2017-08-14 01:45 UTC
I working with sub resources, and now swagger page look very messy.

Subresource should not appear on target groups. Any setting to prevent this? 

![screen shot 2017-08-14 at 8 39 41 am](https://user-images.githubusercontent.com/25856838/29255627-646c5b42-80cd-11e7-86b7-c10d4650cdd5.png)

**Comment by synchr0n123r** [comment] 2017-08-14 01:48
![screen shot 2017-08-14 at 8 39 41 am](https://user-images.githubusercontent.com/25856838/29255613-51a2fa0c-80cd-11e7-9790-13139084fcb5.png)

**Comment by soyuka** [comment] 2017-08-14 14:04
Looks fine 😆

**Comment by synchr0n123r** [comment] 2017-08-15 15:08
also consider to add depth settings.
I found we can have same naming on sub resource

**Comment by soyuka** [comment] 2017-08-16 08:37
I'd like a case reproduction for name collision if you have one!

**Comment by synchr0n123r** [comment] 2017-08-17 00:23
sorry typo...
i mean we can't have same sub resource name.
example:
i have 2 entities, that 2 entities have "likes" sub resources. 
/contents/{id}/likes
/events/{id/likes

when i want to make both as "user" sub resources, its not allowed.
/users/{id}/events/{id}**/likes**
/users/{id}/contents/{id}**/likes**

we should allow this practices.

**Comment by synchr0n123r** [comment] 2017-09-01 13:15
@soyuka : do you have suggestion for quick fix for this?

**Comment by soyuka** [comment] 2017-09-01 13:29
@synchr0n123r this look like a bug, I need to take a closer look.

**Comment by soyuka** [comment] 2017-09-01 14:15
@synchr0n123r I don't get it, this should be good. All you have to do is add a `Subresource` on `Events` and `Contents` in the `User` entity. 

See the referenced commit, that's exactly what the test is trying to do and I'm getting the correct results.

Please give me a reproduction case in a `gist` if you can.

**Comment by soyuka** [comment] 2017-10-24 15:52
Any updates?

**Comment by Nightbr** [comment] 2017-11-22 14:55
Hey same issue here, I think it should be nice to control the depth of subresources.

For example, If I have /api/publications/{id}/comments and /api/users/{id}/publications, I don't want to generate the route /api/users/{id}/publications/{publications}/likes. 

I tried by adding @MaxDepth(1) annotation but no effect (I'm pretty sure it's because MaxDepth is related to the serializer and not the route generator but I give it a try ^^) 

Thanks!

**Comment by soyuka** [comment] 2017-11-22 15:35
> I tried by adding @maxdepth(1) annotation but no effect (I'm pretty sure it's because MaxDepth is related to the serializer and not the route generator but I give it a try ^^)

No you're right. Should be pretty easy to implement in https://github.com/api-platform/core/blob/091865fecf69e9c60bd77b8c6c8eb1c31bce4249/src/Operation/Factory/SubresourceOperationFactory.php#L64 

Feel free to PR on this :).

**Comment by Nightbr** [comment] 2017-11-22 15:37
@soyuka sure I am on it with also a bug with normalization_context with subresources:
https://github.com/api-platform/api-platform/issues/440

**Comment by Nightbr** [comment] 2018-03-05 08:56
I think we should close this with the PR merged!

**Closed** 2018-03-05 08:59 UTC
Labels: enhancement, question
