### ISSUE TITLE
Request parsing with timezoned datetime in CollectionNormalizer (v1.1.0)

### ISSUE THREAD

**Issue by blt909** [api-platform/core#596] opened 2016-07-06 14:52 UTC
Hi,

We use the date filter pass a datetime with timezone.
Here's an exemple query : 
`/api/web_posts/15782/comments?createdAt%5Bbefore%5D=2016-07-06T15:11:05%2B02:00&order%5BcreatedAt%5D=desc`
The timezone is correctly encoded `%2B02:00` for `+02:00`.

In API return, I have **hydra:nextPage**, **hydra:firstPage** and **hydra:lastPage** mostly url encoded excepting the timezone part of the date : 
`api/web_posts/15782/comments?createdAt%5Bbefore%5D=2016-07-06T15%3A11%3A05+02%3A00&order%5BcreatedAt%5D=desc&page=2`

If I rely on this query without replacing `+` by `%2B`, then I get this error from the DateFilter : 
`DateTime::__construct(): Failed to parse time string (2016-07-06T15:11:05 02:00) at position 20 (0): Double time specification`.

I think there's something in Util\RequestParser.php but I'm not sure 

Thanx

**Comment by soyuka** [comment] 2016-07-06 15:38
Got this too with current master version, I ditched the time because I didn't need it for my query and didn't inspect this further. 

Note that we have no tests with a full date time in https://github.com/api-platform/core/blob/master/features/doctrine/date-filter.feature, which might reproduce this issue.

**Comment by rimi-itk** [comment] 2016-08-06 19:49
I've run into this issue as well and have investigated a little:

RequestParser::parseRequestParams urldecodes its argument before passing it to parse_str. However, parse_str urldecodes both keys and values (cf. http://php.net/manual/en/function.parse-str.php#82675) and therefore we get the values in the query string urldecoded twice (%2B → + → ' ').

Not urldecoding the input, i.e. removing the line https://github.com/api-platform/core/blob/master/src/Util/RequestParser.php#L54, breaks 3 tests in https://github.com/api-platform/core/blob/master/features/doctrine/date_filter.feature, but I'm not yet sure why.

**Comment by soyuka** [comment] 2016-08-20 17:44
This is fixed by #672 right?

**Closed** 2016-08-24 03:27 UTC
Labels: bug
