### ISSUE TITLE
JSON Api response body does not follow specification in Version 2.2.0 beta 1

### ISSUE THREAD

**Issue by plantigrate** [api-platform/core#1669] opened 2018-01-29 19:43 UTC
Is there a reason that the response body has been implemented like:

```
{
    "data": [{
        "type": "articles",
        "id": "/articles/1",
        "attributes": {
            "_id": "1"
            "title": "JSON API paints my bikeshed!"
        }
    }]
}
```

Rather than as per the specification :

```
{
    "data": [{
        "type": "articles",
        "id": "1",
        "attributes": {
            "title": "JSON API paints my bikeshed!"
        },
        "links": {
            "self": "http://example.com/articles/1"
        }
    }]
}
```

It seems like there wouldn't be too many changes required in `ApiPlatform\Core\JsonApi\Serializer\ItemNormalizer` to initially bring this inline with the specification. I started making a few changes earlier but thought I would check if this was by design?

**Comment by dunglas** [comment] 2018-02-02 15:45
Using a string as id looks valid according to [the spec](http://jsonapi.org/format/#document-resource-identifier-objects). We use this behavior consistently in all formats (even GraphQL, which isn't a hypermedia format) because having the public ID as an IRI allows:

* To deal easily with compound keys
* To easily reference the same resources in several formats (hypermedia or not), for instance, retrieve some data using GraphQL, then apply REST operations using JSON API because the IRI of the data (the public id is always unique, and always an IRI, even if internally the database use a composed primary key for instance).

However, the lack of `self` link looks indded suspicious. Any hint @meyerbaptiste @Simperfit?

**Comment by jonday-simitive** [comment] 2018-02-02 16:10
@dunglas If the ID is returned as an IRI for consistency I can work around it as have always assumed in other code written prior to using Api Platform to consume JSON API responses that the ID would only be the ID not a link to the resource. But if this is by design then ok to work with this. 

I thought I read somewhere that Api Platform uses the Hydra '@id' for IRI across all content-types but perhaps I am confused about that. Plus Hydra isn't something I've really looked into so a bit in the dark about this.

Though I also don't see the id being returned as a IRI in HAL or LD-JSON 

Example Hal:

```
{
      "_links": {
        "self": "/api/channels",
        "item": [
          {
            "href": "/api/channels/1"
          },
        ]
      },
      "totalItems": 1,
      "itemsPerPage": 25,
      "_embedded": {
        "item": [
          {
            "_links": {
              "self": {
                "href": "/api/channels/1"
              }
            },
            "id": 1,
            "name": "Something"
          }
        ]
      }
    }
```

Example LD-JSON

```
{
  "@context": "/api/contexts/Channel",
  "@id": "/api/channels",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/api/channels/1",
      "@type": "Channel",
      "id": 1,
      "name": "Something"
    }
  ],
  "hydra:totalItems": 4,
  "hydra:search": {
    "@type": "hydra:IriTemplate",
    "hydra:template": "/api/channels{?id,id[],name}",
    "hydra:variableRepresentation": "BasicRepresentation",
    "hydra:mapping": [
      {
        "@type": "IriTemplateMapping",
        "variable": "id",
        "property": "id",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "id[]",
        "property": "id",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "name",
        "property": "name",
        "required": false
      }
    ]
  }
}
```
Can you also tell me more about this new option in V2.2 `allow_plain_identifiers` could this help me?!

**Comment by dunglas** [comment] 2018-02-02 16:14
Well, let me double-check this. `allow_plain_identifiers` has been added (even if I not a fond of this) to prevent this behavior and allow to return the `raw` id.

**Comment by meyerbaptiste** [comment] 2018-02-09 15:52
> However, the lack of self link looks indeed suspicious.

I think it's an omission because IIRC the self link exists for collections. Anyway according to the spec it's not mandatory. The JSON is totally valid here.

The addition of the self link for items is welcome @plantigrate.

**Comment by Simperfit** [comment] 2018-04-24 11:07
Closing as we got no feedbacks.

**Closed by Simperfit** 2018-04-24 11:07 UTC
