### ISSUE TITLE
BC Break on SearchFilter with date as input

### ISSUE THREAD

**Issue by Nek-** [api-platform/core#4128] opened 2021-03-10 18:58 UTC
**API Platform version(s) affected**: x.y.z

**Description**  

If you use dates with the search filter, this was supported, it now triggers an exception. This is because previously the type was not always sent with the doctrine parameter, and doctrine was considering the date as string type (which is valid when you have a string like `2021-01-12` as input).

**How to reproduce**  

If you have the following filter configured on an entity, it will break:

```php
/**
 * ...
 * @ApiFilter(SearchFilter::class, properties={"something.id": "exact", "date": "exact"})
 */
```

**Possible Solution**  

Add support for dates, which is a special case that is not that simple because it requires to manage `date`, `datetime`, `datetime_immutable` and so on.

**Comment by alanpoulain** [comment] 2021-03-10 19:12
Related: https://github.com/api-platform/core/issues/241
Maybe adding an exception when using a search filter in a date property would be a good thing?

**Comment by soyuka** [comment] 2021-03-11 13:59
> If you use dates with the search filter, this was supported, it now triggers an exception. This is because previously the type was not always sent with the doctrine parameter, and doctrine was considering the date as string type (which is valid when you have a string like 2021-01-12 as input).

This was never officialy supported as there is a DateFilter that should be used for dates no?

**Comment by Nek-** [comment] 2021-03-12 09:03
It actually was working.

**Comment by bendavies** [comment] 2021-03-12 16:52
The `DateFilter` does not support exact matching `date=2021-03-12`, but only `before` and `after` filtering ('<=','<','>=', '>'), so we use `SearchFilter` instead, which worked previously. 
Now the type is inferred, added in https://github.com/api-platform/core/pull/3774
so this will be thrown:
```
Doctrine\DBAL\Types\ConversionException
Could not convert PHP value '2020-12-31' of type 'string' to type 'date_immutable'. Expected one of the following types: null, DateTimeImmutable
```

what is the way forward here? add `=` support to DateFilter?

**Comment by alanpoulain** [comment] 2021-03-12 16:58
@bendavies you can combine the date filter like this to do so:
`?date[before]=2021-03-12&date[after]=2021-03-12`
Maybe we should document it?

**Comment by bendavies** [comment] 2021-03-12 17:02
that is pretty terrible DX, don't you think?
I'm happy to PR a change to the datefilter.

**Comment by alanpoulain** [comment] 2021-03-12 17:08
Not sure why there is no `equal`. Maybe @dunglas has an idea?
Personally, I'm OK of adding `equal`.

**Comment by bendavies** [comment] 2021-03-12 17:16
hmm, unfortunately it would be `date[equal]=2020-12-31`, not matching the existing behavior of `date=2020-12-31`. would have to do some jiggery pokery to fix the BC break here.

**Comment by bendavies** [comment] 2021-03-12 17:20
I think I'd like some guidance on what would be acceptable before working on a PR.

**Comment by alanpoulain** [comment] 2021-03-12 17:20
Why wouldn't it match the behavior of the search filter?

**Comment by bendavies** [comment] 2021-03-12 17:21
because API consumers would have to start using `date[equal]=2020-12-31` instead of what they currently use, `date=2020-12-31`

**Comment by alanpoulain** [comment] 2021-03-12 17:25
Oh yes sure, the format is not exactly the same.
I understand that it can be considered as a BC break, but using the search filter for dates is a twisted usage, not documented and not tested.
We really need to clarify this usage.

**Comment by bendavies** [comment] 2021-03-12 17:30
I think we can make `SearchFilter` ignore dates, and let `DateFilter` handle both formats:
`date[equal]=2020-12-31`and `date=2020-12-31`.
this would mitigate the BC break.
WDYT?

**Comment by soyuka** [comment] 2021-03-12 17:46
IMHO #3774 should not have break this anyways especially in a patch I'd be in favor of:
- reverting the part of the PR that breaks this
- add this to the next minor (future 2.7) but add an alternative

**Comment by alanpoulain** [comment] 2021-03-12 18:10
I'm personally not OK of reverting it. If needed we can just handle the case of the `date` type (we use a `string` or `null` type instead).
And if there is no test covering a used but not documented feature, we cannot prevent BC breaks.

Also, I think having both formats would add more confusion with the search filter.

**Comment by soyuka** [comment] 2021-03-12 23:22
https://github.com/api-platform/core/pull/4134 would that go @alanpoulain ?

**Comment by alanpoulain** [comment] 2021-03-12 23:45
Yes something like this would do.

**Comment by soyuka** [comment] 2021-03-13 09:23
I tried fixing this without reverting but it's not possible there are too many use cases were it doesn't work + #3774 adds a deprecation. Let's add this on 2.7 only.

**Comment by alanpoulain** [comment] 2021-03-13 11:26
I really don't think we should:
- there has been some refactoring and it would be hard to revert
- adding this fix in 2.7 would not solve the underlying issue

The problem is that some types need conversion (from PHP to DB), some need not. For instance:
- Binary UUID always converts the type: https://github.com/ramsey/uuid-doctrine/blob/15961598d1fb440444c345b41aec9b1e09ab91b7/src/UuidBinaryType.php#L101-L103
- Elao Enum doesn't convert it (it's the dev responsibility): https://github.com/Elao/PhpEnums/blob/69a74a3a0bd69c287b7234544c031d42bbe560a7/src/Bridge/Doctrine/DBAL/Types/AbstractEnumType.php#L57

But you are right that it breaks much more things that I thought.
My proposal is to have a whitelist of types that need a conversion (only binary uuid for now).
For the other types, we don't set the type and it will be compared as a string like before.

If you are okay with this proposal @soyuka, I will make a PR.

**Comment by soyuka** [comment] 2021-03-13 14:01
> there has been some refactoring and it would be hard to revert

I did the revert it wasn't so hard see: https://github.com/api-platform/core/pull/4134 and we don't deprecate things in patches / bug fixes, #3774 adds a deprecation so definitely :-1:  to do so. 

> The problem is that some types need conversion (from PHP to DB), some need not.  Binary UUID , Elao enums

Although both don't have `canRequireSQLConversion`... 

>  My proposal is to have a whitelist of types that need a conversion (only binary uuid for now).

Why not but I still think that this deserves a new PR that doesn't deprecate anything if it's a bug fix, adding support for UuidBinary is a new feature (what #3774 does). IMHO we should always have types when adding the parameter.

**Comment by alanpoulain** [comment] 2021-03-13 15:29
Shouldn't we document somewhere that adding a deprecation for patches / bug fixes cannot be done? For instance in `CONTRIBUTING.md`?

Are you sure that `canRequireSQLConversion` corresponds to the same thing? It seems to me that it is a very specific thing:
> Does working with this column require SQL conversion functions?

But if we always add types, it would cause the same BC for 2.7.

**Comment by soyuka** [comment] 2021-03-13 17:10
> But if we always add types, it would cause the same BC for 2.7. 

Indeed and we then need to find an alternative on the DateFilter :)

**Comment by bendavies** [comment] 2021-04-05 19:30
@soyuka can this be closed? #4134

**Comment by regisnew** [comment] 2021-04-10 23:35
Same problem here:

Could not convert PHP value \u00272021-04-10\u0027 of type \u0027string\u0027 to type \u0027date\u0027. Expected one of the following types: null, DateTime

` * @ApiFilter(
 *     SearchFilter::class,
 *     properties={
 *         "dataNecessidade":"exact"
 *     }
 * )`

**Comment by regisnew** [comment] 2021-04-10 23:36
Downgrading api-platform/core to 2.6.2 works for me.

**Comment by guilliamxavier** [comment] 2021-04-13 08:50
Should be fixed in 2.6.4 now

**Comment by alanpoulain** [comment] 2021-04-13 08:57
That's right. I'm closing this issue. I you have the same issue, please make sure you use the 2.6.4 version.

**Closed by alanpoulain** 2021-04-13 08:57 UTC

**Comment by mrtnzagustin** [comment] 2021-10-14 10:54
Does the SearchFilter (with "exact)" works with a datetime field?
