### ISSUE TITLE
Subresource routes missing

### ISSUE THREAD

**Issue by thasmo** [api-platform/core#2103] opened 2018-07-15 13:25 UTC
Resource:
```php

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ApiResource
 */
class User
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Region", inversedBy="users", fetch="EAGER", cascade={"persist"})
     * @ApiSubresource(maxDepth=1)
     */
    private $region;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Player", mappedBy="user", fetch="EXTRA_LAZY", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ApiSubresource(maxDepth=1)
     */
    private $players;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Enqueuement", mappedBy="user", fetch="EXTRA_LAZY", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ApiSubresource(maxDepth=1)
     */
    private $enqueuements;
}
```

Routes:
```
  api_users_get_collection                   GET      ANY      ANY    /users.{_format}
  api_users_post_collection                  POST     ANY      ANY    /users.{_format}
  api_users_get_item                         GET      ANY      ANY    /users/{id}.{_format}
  api_users_delete_item                      DELETE   ANY      ANY    /users/{id}.{_format}
  api_users_put_item                         PUT      ANY      ANY    /users/{id}.{_format}
  api_users_region_get_subresource           GET      ANY      ANY    /users/{id}/region.{_format}
```

Why are routes for `players` and `enqueuements` missing?

**Comment by thasmo** [comment] 2018-07-15 14:37
It seems that for all entities only the first `ApiSubresource` annotation works, all subsequent annotations have no effect.

**Comment by thasmo** [comment] 2018-07-15 18:09
If I actually remove `@ApiSubresource(maxDepth=1)` from the `$region` property, a route for `$players` is available and working, but the route for `$enqueuements` is still missing.

**Comment by dunglas** [comment] 2018-07-15 22:47
It looks like a big issue to me. Do you think you can try to fix?

**Comment by soyuka** [comment] 2018-07-25 15:59
duplicate of https://github.com/api-platform/core/issues/1711 fixed in https://github.com/api-platform/core/commit/0eb9602de46073f8c3360c55914754b9e694b4cc should be available in 2.2 and 2.3

What's your version?

**Comment by thasmo** [comment] 2018-08-14 22:06
@soyuka I'm on `api-platform/api-pack:1.1.0` and `api-platform/core:2.3.0`.

**Comment by Nightbr** [comment] 2018-08-20 09:07
Hey, I can reproduce this bug with a test, I'm working on a fix...

**Comment by Nightbr** [comment] 2018-08-20 13:13
Fixed and merged, will be out in next released :ok_hand:

**Comment by Nightbr** [comment] 2018-08-23 06:03
hey @thasmo can you test with the last release https://github.com/api-platform/core/releases/tag/v2.3.1 and close this issue if it works for you!

**Closed as completed** 2018-08-23 09:21 UTC
