### ISSUE TITLE
Object root structure support for GetCollection attributes instead of list.

### ISSUE THREAD

**Issue by sergiuionescu** [api-platform/core#5943] opened 2023-11-03 11:41 UTC
**Description**  
As a developer I would like to add metadata to my collection responses when returning an application/json response via the ApiPlatform\Metadata\GetCollection::$output parameter.

**Example**  
Currently the GetCollection attribute can only be used to define a response that is a list at the root level.
Ex:
`new GetCollection(controller: GetUserActionController::class,)`
OpenApi response example:
```
[
  {
    "email": "example@example.test",
    "country": "string",
    "company": "string",
    "firstName": "string",
    "lastName": "string",
  }
]
```
This is fine for a very simple use case, but most of the time you want to include some metadata with this response. The best example here would be including pagination.

Let's try defining the output to a DTO that structures the paginated response:

UserPaginatedResponse.php:
```
...
#[ApiResource]
class UserPaginatedResponse extends PaginatedResponse
{
    #[ApiProperty(required: true)]
    #[Groups(['list'])]
    /** @var User[] */
    public array $data;
}
```
User.php
```
...
#[ApiResource(
...
operations: [
new GetCollection(controller: GetUserActionController::class, output: UserPaginatedResponse::class),
]
...
```
The actual result in the documentation here is:
```
[
  {
    "data": [
      {
        "email": "example@example.test",
        "country": "string",
        "company": "string",
        "firstName": "string",
        "lastName": "string",      
      }
    ],
    "metadata": {
      "items": 0,
      "totalPages": 0,
      "totalItems": 0,
      "currentPage": 0,
      "totalItemsPerPage": 0
    }
  }
]
```

What I want to be able to do with this is:
```
  {
    "data": [
      {
        "email": "example@example.test",
        "country": "string",
        "company": "string",
        "firstName": "string",
        "lastName": "string",      
      }
    ],
    "metadata": {
      "items": 0,
      "totalPages": 0,
      "totalItems": 0,
      "currentPage": 0,
      "totalItemsPerPage": 0
    }
  }
```

The current workaround for this is using the ApiPlatform\Metadata\Get operation, but with the inconveniance that GET /users/{id} must be available and defined before this pseudo collection get is defined(see \ApiPlatform\JsonSchema\SchemaFactory::findOperationForType).

I realize that changing the designation for GetCollection::$output is a breaking change, but I think adding a new parameter boolean $forceOutputObject would enable the desired behaviour.

**Comment by soyuka** [comment] 2023-11-06 08:38
Hi why don't you use JSON API or JSON LD to do so? there are specifications on how to define such metadata already and they're part of API Platform.  
Then, if you look at our code we do this inside symfony normalizers and you should probably do the same, although I don't recommend re-inventing the wheel. Closing as this is not a bug.

**Closed by soyuka** 2023-11-06 08:38 UTC

**Comment by sergiuionescu** [comment] 2023-11-06 09:06
@soyuka Normalizers only take care of the actual response and not documenting the response structure. I was referring to the endpoint documentation above, as the response itself can be shaped with ease by using the $output parameter alone.

I want a way to align the documentation while still relying on ApiProperty attributes as opposed to using \ApiPlatform\Metadata\HttpOperation::__construct(openapiContext) which will be deprecated (which I consider a good thing) or OpenApiFactoryInterface.

**Comment by soyuka** [comment] 2023-11-06 10:06
For documenting you can either specify the openapi operation within attributes (or extending metadata). Then you can also extend (decorate) the OpenAPI factory.

**Comment by sergiuionescu** [comment] 2023-11-06 11:03
Thanks for the reply, I understand this is out of scope and there are indeed a couple of workarounds including the one I initially mentioned. If I bump my head agains a blocking issue, I'll try to come back with a MR.
