### ISSUE TITLE
Add an item to array collection.

### ISSUE THREAD

**Issue by yakobabada** [api-platform/core#2535] opened 2019-02-20 12:25 UTC
I have a Question entity that relates 'OneToMany' with Answer. The question is how to create a custom endpoint with path='question/{id}/add_answer' to add an answer to a certain question.

My first thought was
- Adding a post in [subresources ](https://api-platform.com/docs/core/operations/#subresources) but it doesn't work.
- Adding custom controller but inside '__invode(data)' I get the question entity back without the new answer.
Any ideas?

**Comment by ilgneroliveira** [comment] 2019-07-19 13:14
any answers on this?

**Comment by teohhanhui** [comment] 2019-07-19 13:34
You can achieve this with a custom operation.

Closing as duplicate of #1628. Please see there for some suggestions and discussion.

**Closed by teohhanhui** 2019-07-19 13:34 UTC
