### ISSUE TITLE
Making Elao Enums work out of the box

### ISSUE THREAD

**Issue by jacraade** [api-platform/core#2936] opened 2019-07-17 10:22 UTC
Hello.

Using [Elao Enums](https://github.com/Elao/PhpEnums) as properties gets the openapi/swagger generator all confused. It always says that the type is string instead of the actual enum type or the type behind the enum (integer in my case). functionally it seems to work fine (as in you pass an integer not a string to the api and it saves it correctly) so that means the enum normalizer does its job.

is there a way to at least make it detect the correct type? (enum support in general seems to be WIP)

currently i'm overwriting it by hand using

```
     * @ApiProperty(
     *     attributes={
     *         "swagger_context"={"type"="integer"},
     *         "openapi_context"={"type"="integer"}
     *     }
     * )
```

but thats not optimal.

i suppose this is just how it is right now with enums not supported out of the box but is there a a better way doing it till they are supported?

**Comment by teohhanhui** [comment] 2019-07-18 11:10
I don't see anything in the [EnumInterface](https://github.com/Elao/PhpEnums/blob/master/src/EnumInterface.php) that allows us to know the type of values. So it's not possible at this time.

**Comment by jacraade** [comment] 2019-07-18 12:15
hmm. what would be needed to make it clear so i could create a pull request for it? a function that returns a php or json type name?

also i guess the [backend binding](https://github.com/Elao/PhpEnums/blob/master/src/Bridge/Doctrine/DBAL/Types/AbstractIntegerEnumType.php#L28) doesn't help because its not a thing that always exists.

**Comment by teohhanhui** [comment] 2019-07-18 14:02
Hmm... It might help actually. They could create a `PropertyInfo` extractor that uses the Doctrine metadata. But I don't lnow how good the `PropertyInfo` component is at combining / merging type information from multiple sources. @dunglas?

**Comment by soyuka** [comment] 2019-07-19 08:45
IMO `propertyinfo` can be easily decorated

**Comment by teohhanhui** [comment] 2019-07-19 08:47
Fair enough.

**Comment by jacraade** [comment] 2019-07-22 10:20
@teohhanhui , ok after some more work i found out that only the get works but the put/post (denormalization) of enum values causes an "This value should be of type MyEnum" error.

i found out that api platform only passes the class name to the normalizer without the namespace (so "MyEnum" not "App\Enum\MyEnum"). This is likely the root issue as even with a custom Normalizer that adds the namespace back to it, it then fails at validation with the same error

**Comment by teohhanhui** [comment] 2019-07-22 10:45
@jacraade That doesn't sound like an API Platform issue. You probably forgot a `use` statement?

**Comment by jacraade** [comment] 2019-07-22 11:19
i think i just solved it. the problem was not the use but the autogenerated `@var \MyEnum` annotation.
never paid attention to it because i didn't imagine it being used. changed it to an absolute path seems to fix it (have to do more tests)

hope php gets native attributes some day and doesn't have to misuse comments 😞 

sorry for the hassle

**Comment by teohhanhui** [comment] 2019-07-22 11:53
Typed properties will be in PHP 7.4 :smile:

**Comment by soyuka** [comment] 2021-02-23 11:07
Closing as duplicate of https://github.com/api-platform/core/issues/2254

**Closed by soyuka** 2021-02-23 11:07 UTC
Labels: question
