### ISSUE TITLE
Changing the Serialization Context Dynamically

### ISSUE THREAD

**Issue by Yoann-TYT** [api-platform/core#1660] opened 2018-01-19 15:18 UTC
Hello,

I use the last version v2.1.5, and when I follow the example, it works for GET / PUT but not for POST calls.

When I `POST` and when `normalization == false`, the subject class is `AppBundle\Serializer\BookContextBuilder`, so it doesn't pass my condition :-/

Everyone get the same problem ?

**Comment by Yoann-TYT** [comment] 2018-01-22 08:13
The example that I talk about is https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-dynamically :)

**Comment by Yoann-TYT** [comment] 2018-01-30 13:55
Nobody has the same problem  ? :-/

**Comment by Nek-** [comment] 2018-03-27 15:45
@Yoann-TYT Please provide more information about your issue (like the code and configuration you used). Because this feature looks ok to me.

**Comment by Simperfit** [comment] 2018-04-09 07:51
As @Nek- said, could you please provide a reproducer? So we could directly test the behaviour.

**Comment by Yoann-TYT** [comment] 2018-05-04 14:25
Thanks for your responses :) 
I think it's a particular case : 
To allow user to fill some fields, I need to check their rights on a property

```
        $subject = $request->attributes->get('data');
        if (
            isset($context['groups']) &&
            $subject instanceof Book &&
            $this->authorizationChecker->isGranted('VIEW', $subject->getAuthor())
        ) {
            $context['groups'][] = 'specific-input';
        }
```

And this code doesn't work for POST method :-/

**Comment by soyuka** [comment] 2019-04-07 09:48
Did you find an answer? As this issue is quite old I'm going to close it but feel free to ping me or to seek for an answer on the api-platform slack (symfony-devs.slack.com)!

**Closed by soyuka** 2019-04-07 09:48 UTC
Labels: question
