### ISSUE TITLE
Not possible to create Many-to-One embedded entities that have constructor

### ISSUE THREAD

**Issue by maks-rafalko** [api-platform/core#2395] opened 2018-12-19 14:15 UTC
Let's consider the example from Behat tests of this repository.

We have `VoDummyCar` that has a collection of `VoDummyInspection[]` entities (with constructor `public function __construct(bool $accepted, VoDummyCar $car...)`.

We already have separate tests that create `VoDummyCar` and `VoDymmyInspection` for particular car

`POST /vo_dummy_car`

https://github.com/api-platform/core/blob/f8693d1619cfafd2b639b349e7cba4861123d3c5/features/serializer/vo_relations.feature#L9-L25

`POST /vo_dummy_inspections`

https://github.com/api-platform/core/blob/f8693d1619cfafd2b639b349e7cba4861123d3c5/features/serializer/vo_relations.feature#L56-L61

# What does not work?

Someone might want to create `VoDummyInspection` entities at the same time when `VoDummyCar` is being created, providing a nested array.

It turned out, that such request does not work with ApiPlatform:

```json
{
    "mileage": 1500,
    "bodyType": "suv",
    "make": "CustomCar",
    "insuranceCompany": {
        "name": "Safe Drive Company"
    },
    "drivers": [],
    "inspections": [
        {
            "performed": "2018-08-24 00:00:00",
            "accepted": false
        }
    ]
}
```

# Expected result

Running the query above, I expect new `VoDummyCar` to be created **as well as** new `VoDummyInspections` to be created for this `VoDummyCar` (in this case - just one entity).

# Actual Result

1. When I modify existing tests - nothing happens. `inspections` key from JSON is ignored (I have added `addInspection` and `removeInspection` methods to make this property writable, but it didn't help).

2. In my project, I get an error something like `Cannot create an instance of VoDummyInspection from serialized data because its constructor requires parameter \"car\" to be present.`

-----

Any suggestions about possible implementation?

**Comment by karser** [comment] 2018-12-19 18:39
1. This is a serializer issue, an array of objects is not deserialized properly. My PR fixes it https://github.com/symfony/symfony/pull/29513 
It's merged but not tagged yet, so use branches, e.g 4.1.x-dev or 4.2.x-dev, etc. 
2. I used to have a similar issue but it's gone when I switched to `api-platform: dev-master`

**Comment by borNfreee** [comment] 2018-12-19 19:01
Thanks for taking the time and commenting. However, this is not the same issue.

If I rewrite the bug with entities from your PR, the issue with the not setting `Zoo` to `Animal`s constructor

```php
class Animal {
    /** @var Zoo */
    private $zoo;

    /** @var string */
    private $name;

    pubic funnction __construct(Zoo $zoo, string $name) {...}
}
```

and `POST /zoos`

```json
{
    "animals": [
        {"name": "Bug"}
    ]
}
```

So the issue is that api-platform can't deserialize `Animal` and pass `Zoo` instance to when one-to-many is used.

**Comment by soyuka** [comment] 2021-02-23 14:45
This looks really specific though and I'd create a custom DataPersister for such need. Are you sure that the normalizer doesn't work properly with Dtos? About constructors the support has been added in recent version, lmk if I need to reopen this. Thanks for your support all these years though :).

**Closed by soyuka** 2021-02-23 14:45 UTC

**Comment by maks-rafalko** [comment] 2022-05-14 13:24
Having the same issue right now in 2022, and found my own issue :)

@soyuka probably you have a new recommendations now with new versions of APIP for this problem?

**Comment by NikDevPHP** [comment] 2023-01-12 12:58
Hello @soyuka any updated on this ?
