### ISSUE TITLE
Non anemic doctrine models are not supported

### ISSUE THREAD

**Issue by Nek-** [api-platform/core#1747] opened 2018-03-05 13:32 UTC
I'd like to write my model this way:

```php
class Mail
{
    private $from;
    private $to;
    private $content;
    public function __construct($from, $to, $content)
    {
        $this->from = $from;
        $this->to = $to;
        $this->content = $content;
    }
}
```

My model looks like this following DDD guidelines.

But with ApiPlatform having this model with a correct (standard) configuration will result in an error of deserialization because fields are not considered as "writable" by the [`DoctrineOrmPropertyMetadataFactory`](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactory.php) class. Which is wrong on a `Serializer` point of view... and even on a Doctrine point of view as this entity is perfectly valid and its fields are also perfectly writable.

To me, this is an issue but @soyuka seems to disagree after a short discussion on slack.

There are many solutions for this problem inside ApiPlatform:
- ~patch the `DoctrineOrmPropertyMetadataFactory`~ 
- patch the `SerializerPropertyMetadataFactory` (after all if I say they are writable, then they are)
- probably many more as there's also a "configuration" that may set the property writable by default (adding its documentation would be a great help)

There's a last thing about adding a custom `PropertyMetadataFactoryInterface` (that still needs some documentation) but I don't think it's relevant as to me, ApiPlatform must support this by default (to be compliant with Doctrine and Symfony)

[edit] this has nothing to do with the `DoctrineOrmPropertyMetadataFactory`.

**Comment by dunglas** [comment] 2018-03-05 13:38
For the record, I'm to support this kind of objects. But it will be a tedious work.

**Comment by greg0ire** [comment] 2018-03-05 13:39
Another possibility if you're stuck might be to create a DTO to represent the writable fields, then validate it with the Validation component, and if it is valid and only then, attempt to update your entity from that.

**Comment by soyuka** [comment] 2018-03-05 14:00
> For the record, I'm to support this kind of objects. But it will be a tedious work.

You mean by using the constructor to set the properties?

**Comment by dunglas** [comment] 2018-03-05 14:00
Yes, some improvements have been done in the Symfony serializer to support this use case.

**Comment by soyuka** [comment] 2018-03-05 14:03
> Yes, some improvements have been done in the Symfony serializer to support this use case.

Though, even with this implemented, these properties will still be considered as readonly if they don't have any setters.

**Comment by dunglas** [comment] 2018-03-05 14:04
Until we patch API Platform :)

**Comment by DonCallisto** [comment] 2018-05-23 06:57
@greg0ire 

> Another possibility if you're stuck might be to create a DTO to represent the writable fields, then validate it with the Validation component, and if it is valid and only then, attempt to create your entity from that.

That's what I did but I notice some "issues": first of all, in documentation you'll see a resource that is the DTO whereas the (i.e.:) `POST` action should refers to *real* resource.
Second, when I get the response back, I need to implement a listener to change every link that present DTO name into real resource name.

If this is the only method here I don't feel that's a good one.
Have you alternative solutions?

If you want to take a look at my solution, here it is https://github.com/DonCallisto/InterNations/tree/api

**Comment by greg0ire** [comment] 2018-05-23 07:20
I'm not sure we should equate resource and entity, there might be some fields you would not want to publicly expose in there

**Comment by greg0ire** [comment] 2018-05-23 07:28
You could see the resource as a representation of the underlying entity is what I'm saying

**Comment by teohhanhui** [comment] 2018-05-23 09:48
@greg0ire Hence representations are not resources, and should not be identified as such.

**Comment by DonCallisto** [comment] 2018-05-23 09:55
@teohhanhui I had a private chat with @greg0ire. We came up with this idea, that's not the best possible as having multiple representations of the same resource should be possible, but could work. 
The idea is to implement a **unique** DTO for every resource that need it and handle write/read fields differently. So in my example I will have `User` that's the original resource, `RegisterUserCommand` that's a DTO I'll use **outside** API (maybe implementing an interface in order to reuse the command handler?), and a `User` (under a different namespace) that represent `User` as "API DTO". This way I can refer this resource in every response (jsonld, uri, and so on) as `user` (name of the resource) and all operations could be done onto this DTO.
Of course there's some work to do to handle the persistance (for sure it works with api platform events, maybe even with DataPersister?) and the denormalization (data provider?) but apart from that, it seems to be the less cumbersome way to handle this situation.

WDYT?

**Comment by teohhanhui** [comment] 2018-05-23 10:39
I think if we're going to support DTOs properly (without introducing a lot of unnecessary plumbing), it might need to be done at the Symfony Serializer level?

**Comment by DonCallisto** [comment] 2018-05-23 10:44
I'm not sure that only serializer level should be involved as DTOs could (and in this case probably should) have validation and a way to transfer data from DTO to the other resource. While DTO validation and serialization could be standardized, for data passage I'm not so confident.

BTW, as in this version we don't have DTOs support, could solution proposed above (I'm gonna try it in the next hours so I can comeback with some working code) a good compromise?

**Comment by dunglas** [comment] 2018-05-23 10:46
Symfony Serializer has now (4.1) everything needed for DTO support. PropertyInfo is being enhanced too (it will be for 4.2): https://github.com/symfony/symfony/pull/26997

Proper support in API Platform is almost finished too thanks to @Nek- and @komik966:
- https://github.com/api-platform/core/pull/1843
- https://github.com/api-platform/core/pull/1749

**Comment by DonCallisto** [comment] 2018-05-23 12:10
@dunglas I like this, moreover I've implemented (in a summary way) first three of your points that helps me a lot with my issue (https://github.com/DonCallisto/InterNations/commit/cb4ef80c47640b9f612df07d349672dd9cb8edcb)

Talking about 

> Symfony Serializer has now (4.1) everything needed for DTO support. PropertyInfo is being enhanced too (it will be for 4.2): symfony/symfony#26997
>
> Proper support in API Platform is almost finished too thanks to @Nek- and @komik966:
>
> #1843
> #1749

I'll take a look when I've finished my implementation with all use case (that are very basic but I would like to see if all of them are implementable)

/cc @greg0ire your idea combined with @dunglas instructions seems to work!

**Comment by teohhanhui** [comment] 2018-05-23 12:15
@dunglas But value objects are not the only thing needed for using DTOs... There needs to be a way to denormalize to the resource class based on a DTO?

**Comment by dunglas** [comment] 2018-05-23 12:16
@teohhanhui IMO it's out of the API Platform's scope, it's the dev responsibility

**Comment by teohhanhui** [comment] 2018-05-23 12:17
Basically to break the round-trip normalize/denormalize assumption that Symfony Serializer makes? I think it should be in Symfony Serializer.

**Comment by joelwurtz** [comment] 2018-05-23 13:21
Yes, but not in its current version, actually it support private property hydrating / reading, but it miss creating the object without calling the constructor or calling it with correct mapping, however this is something planned.

**Comment by rafix** [comment] 2019-01-10 14:33
@komik966 if standard entities are not registered as ApiResources, how are you handling read operations?

**Comment by er1z** [comment] 2019-01-10 14:36
@rafix — not so sure if understood right but API Platform has a possibility to create own data sources and DTOs handling. You can use no Doctrine entity in API and still get the job done.

**Comment by komik966** [comment] 2019-01-10 16:49
@rafix in my description above i used term "command" - it is intended to change system state.
For pure read operations on non entities i prefer using data providers (especially with `ApiPlatform\Core\DataProvider\RestrictedDataProviderInterface`). But if your need is only to use constructor, you will not have to do such extra work - api-platform has support for it on master branch, but this has not been released yet.

**Comment by rafix** [comment] 2019-01-11 07:05
@komik966 @er1z But, I want to use the doctrine entities as read models, and Commands to write operations. The problem is the required item get definition in Commands make no sense to me... cc @dunglas ???

**Comment by soyuka** [comment] 2019-04-07 09:55
Since 2.4 we support objects that aren't resources and we handle DTO's with inputs/outputs. Closing this as fixed, please don't hesitate to ping me if you need more informations.

**Closed by soyuka** 2019-04-07 09:55 UTC
Labels: Has a PR, enhancement
